"""PPT generator action registrations."""
from __future__ import annotations

from typing import Any

from app.actions.schema import schema_object


def register_ppt_actions(registry: Any) -> None:
    registry.register_adapter_action(
        "ppt.templates.list",
        "List built-in user PPT slide templates.",
        "ppt",
        "ppt_templates_list",
        params_schema=schema_object(),
        mutating=False,
        requires_owner=False,
        changed=False,
        async_kind="ppt",
        dry_summary="available PPT templates would be listed",
    )
    registry.register_adapter_action(
        "ppt.template.apply",
        "Apply a built-in template to the current PPT slide.",
        "ppt",
        "ppt_apply_template",
        params_schema=schema_object(
            {
                "template_id": {"type": "string"},
            },
            required=("template_id",),
        ),
        required=("template_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT template would be applied to the current slide",
    )
    registry.register_adapter_action(
        "ppt.deck.apply_template",
        "Apply a built-in template to the current PPT slide.",
        "ppt",
        "ppt_apply_template",
        params_schema=schema_object({"template_id": {"type": "string"}}, required=("template_id",)),
        required=("template_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT template would be applied to the current slide",
    )
    registry.register_adapter_action(
        "ppt.project.create",
        "Create a new PPT project from a built-in template.",
        "ppt",
        "ppt_project_create",
        params_schema=schema_object(
            {
                "template_id": {"type": "string"},
                "title": {"type": "string"},
                "path": {"type": "string"},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT project would be created",
    )
    registry.register_adapter_action(
        "ppt.project.open",
        "Open a TigerCapture PPT project file.",
        "ppt",
        "ppt_project_open",
        params_schema=schema_object({"path": {"type": "string"}}, required=("path",)),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT project would be opened",
    )
    registry.register_adapter_action(
        "ppt.deck.from_prompt",
        "Create an editable PPT deck from a short prompt.",
        "ppt",
        "ppt_deck_from_prompt",
        params_schema=schema_object(
            {
                "prompt": {"type": "string"},
                "title": {"type": "string"},
                "template_id": {"type": "string"},
                "max_slides": {"type": "integer", "minimum": 1},
                "path": {"type": "string"},
            },
            required=("prompt",),
        ),
        required=("prompt",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT deck would be created from a prompt",
    )
    registry.register_adapter_action(
        "ppt.deck.from_timeline",
        "Create an editable PPT deck from the current editor timeline.",
        "ppt",
        "ppt_deck_from_timeline",
        params_schema=schema_object(
            {
                "title": {"type": "string"},
                "max_slides": {"type": "integer", "minimum": 1},
                "path": {"type": "string"},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT deck would be created from the editor timeline",
    )
    registry.register_adapter_action(
        "ppt.project.save",
        "Save the current PPT project.",
        "ppt",
        "ppt_project_save",
        params_schema=schema_object({"path": {"type": "string"}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT project would be saved",
    )
    registry.register_adapter_action(
        "ppt.project.save_as",
        "Save the current PPT project to a new path.",
        "ppt",
        "ppt_project_save_as",
        params_schema=schema_object({"path": {"type": "string"}}, required=("path",)),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT project would be saved as a new file",
    )
    registry.register_adapter_action(
        "ppt.deck.snapshot",
        "Read the current PPT generator deck, slides, and editable elements for AI editing.",
        "ppt",
        "ppt_deck_snapshot",
        params_schema=schema_object({"include_metadata": {"type": "boolean"}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT deck snapshot would be read",
    )
    registry.register_adapter_action(
        "ppt.deck.validate",
        "Validate the current PPT generator deck for export-readiness issues.",
        "ppt",
        "ppt_deck_validate",
        params_schema=schema_object(),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT deck validation issues would be read",
    )
    registry.register_adapter_action(
        "ppt.deck.import_pptx",
        "Import a PPTX file into the user PPT generator as an editable deck.",
        "ppt",
        "ppt_deck_import_pptx",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "asset_dir": {"type": "string"},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPTX file would be imported into the PPT editor",
    )
    registry.register_adapter_action(
        "ppt.deck.actor_posters.generate",
        "Generate cached poster images for PPT video/3D/MMD/media actors.",
        "ppt",
        "ppt_deck_actor_posters_generate",
        params_schema=schema_object({"force": {"type": "boolean"}}),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT actor poster images would be generated",
    )
    registry.register_adapter_action(
        "ppt.deck.export_pptx",
        "Export the current PPT generator deck as a PPTX file.",
        "ppt",
        "ppt_deck_export_pptx",
        params_schema=schema_object({"path": {"type": "string"}}, required=("path",)),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT deck would be exported as PPTX",
    )
    registry.register_adapter_action(
        "ppt.deck.export_pdf",
        "Export the current PPT generator deck as a PDF file.",
        "ppt",
        "ppt_deck_export_pdf",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "backend": {"type": "string", "enum": ["auto", "libreoffice", "powerpoint", "powerpoint_com"]},
                "timeout_sec": {"type": "integer", "minimum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT deck would be exported as PDF",
    )
    registry.register_adapter_action(
        "ppt.deck.export_video",
        "Export the current PPT generator deck as an MP4 video.",
        "ppt",
        "ppt_deck_export_video",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "fps": {"type": "integer", "minimum": 1, "maximum": 120},
                "width": {"type": "integer", "minimum": 16},
                "height": {"type": "integer", "minimum": 16},
                "audio_path": {"type": "string"},
                "audio_bitrate": {"type": "string"},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT deck would be exported as MP4 video",
    )
    registry.register_adapter_action(
        "ppt.deck.history",
        "Read the current PPT generator undo/redo and recovery status.",
        "ppt",
        "ppt_deck_history",
        params_schema=schema_object(),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current PPT history status would be read",
    )
    registry.register_adapter_action(
        "ppt.deck.undo",
        "Undo the latest PPT generator deck edit.",
        "ppt",
        "ppt_deck_undo",
        params_schema=schema_object(),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="latest PPT edit would be undone",
    )
    registry.register_adapter_action(
        "ppt.deck.redo",
        "Redo the latest undone PPT generator deck edit.",
        "ppt",
        "ppt_deck_redo",
        params_schema=schema_object(),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="latest undone PPT edit would be redone",
    )
    registry.register_adapter_action(
        "ppt.deck.autosave",
        "Write an immediate PPT generator recovery copy.",
        "ppt",
        "ppt_deck_autosave",
        params_schema=schema_object(),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT recovery copy would be written",
    )
    registry.register_adapter_action(
        "ppt.deck.recovery.list",
        "List available PPT generator autosave/recovery copies.",
        "ppt",
        "ppt_deck_recovery_list",
        params_schema=schema_object({"limit": {"type": "integer", "minimum": 1}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT recovery candidates would be listed",
    )
    registry.register_adapter_action(
        "ppt.deck.recovery.open",
        "Open a PPT generator autosave/recovery copy as an unsaved deck.",
        "ppt",
        "ppt_deck_recovery_open",
        params_schema=schema_object({"path": {"type": "string"}}),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT recovery copy would be opened",
    )
    registry.register_adapter_action(
        "ppt.deck.recovery.delete",
        "Delete a PPT generator autosave/recovery copy.",
        "ppt",
        "ppt_deck_recovery_delete",
        params_schema=schema_object({"path": {"type": "string"}}, required=("path",)),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ppt",
        dry_summary="PPT recovery copy would be deleted",
    )
    registry.register_adapter_action(
        "ppt.media_pool.list",
        "List assets in the current PPT workspace media pool.",
        "ppt",
        "ppt_media_pool_list",
        params_schema=schema_object(),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT media-pool assets would be listed",
    )
    registry.register_adapter_action(
        "ppt.media_pool.add",
        "Add a file to the current PPT workspace media pool.",
        "ppt",
        "ppt_media_pool_add",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "kind": {"type": "string"},
                "name": {"type": "string"},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="file would be added to the PPT media pool",
    )
    registry.register_adapter_action(
        "ppt.media_pool.insert",
        "Insert a PPT media-pool asset onto the current slide.",
        "ppt",
        "ppt_media_pool_insert",
        params_schema=schema_object(
            {
                "asset_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
            required=("asset_id",),
        ),
        required=("asset_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT media-pool asset would be inserted onto a slide",
    )
    registry.register_adapter_action(
        "ppt.media_pool.remove",
        "Remove an asset from the current PPT workspace media pool.",
        "ppt",
        "ppt_media_pool_remove",
        params_schema=schema_object(
            {
                "asset_id": {"type": "string"},
            },
            required=("asset_id",),
        ),
        required=("asset_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT media-pool asset would be removed",
    )
    registry.register_adapter_action(
        "ppt.slide.add",
        "Add a slide to the current PPT deck.",
        "ppt",
        "ppt_add_slide",
        params_schema=schema_object(
            {
                "title": {"type": "string"},
                "layout_id": {"type": "string"},
                "duration_ms": {"type": "integer", "minimum": 1},
                "index": {"type": "integer", "minimum": 0},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide would be added",
    )
    registry.register_adapter_action(
        "ppt.slide.duplicate",
        "Duplicate a slide in the current PPT deck.",
        "ppt",
        "ppt_duplicate_slide",
        params_schema=schema_object(
            {
                "slide_id": {"type": "string"},
                "index": {"type": "integer", "minimum": 0},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide would be duplicated",
    )
    registry.register_adapter_action(
        "ppt.slide.remove",
        "Remove a slide from the current PPT deck.",
        "ppt",
        "ppt_delete_slide",
        params_schema=schema_object({"slide_id": {"type": "string"}}),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide would be removed",
    )
    registry.register_adapter_action(
        "ppt.slide.move",
        "Move a slide to a new deck index.",
        "ppt",
        "ppt_move_slide",
        params_schema=schema_object(
            {
                "slide_id": {"type": "string"},
                "index": {"type": "integer", "minimum": 0},
            },
            required=("slide_id", "index"),
        ),
        required=("slide_id", "index"),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide would be moved",
    )
    registry.register_adapter_action(
        "ppt.slide.update",
        "Update a slide's title, layout, duration, notes, transition, background, or metadata.",
        "ppt",
        "ppt_update_slide",
        params_schema=schema_object(
            {
                "slide_id": {"type": "string"},
                "title": {"type": "string"},
                "layout_id": {"type": "string"},
                "duration_ms": {"type": "integer", "minimum": 1},
                "speaker_notes": {"type": "string"},
                "transition": {"type": "string"},
                "background": {"type": "string"},
                "metadata": {"type": "object", "additionalProperties": True},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide would be updated",
    )
    registry.register_adapter_action(
        "ppt.slide.set_layout",
        "Set the current or specified PPT slide layout id.",
        "ppt",
        "ppt_set_slide_layout",
        params_schema=schema_object({"slide_id": {"type": "string"}, "layout_id": {"type": "string"}}, required=("layout_id",)),
        required=("layout_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide layout would be updated",
    )
    registry.register_adapter_action(
        "ppt.slide.set_duration",
        "Set the current or specified PPT slide duration in milliseconds.",
        "ppt",
        "ppt_set_slide_duration",
        params_schema=schema_object(
            {"slide_id": {"type": "string"}, "duration_ms": {"type": "integer", "minimum": 1}},
            required=("duration_ms",),
        ),
        required=("duration_ms",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide duration would be updated",
    )
    registry.register_adapter_action(
        "ppt.slide.set_notes",
        "Set the current or specified PPT slide speaker notes.",
        "ppt",
        "ppt_set_slide_notes",
        params_schema=schema_object({"slide_id": {"type": "string"}, "speaker_notes": {"type": "string"}}, required=("speaker_notes",)),
        required=("speaker_notes",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT slide notes would be updated",
    )
    registry.register_adapter_action(
        "ppt.element.add_text",
        "Add a text box element to the current PPT slide.",
        "ppt",
        "ppt_add_text_element",
        params_schema=schema_object(
            {
                "text": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "font_size": {"type": "integer", "minimum": 8},
                "color": {"type": "string"},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT text element would be added",
    )
    registry.register_adapter_action(
        "ppt.element.add_image",
        "Add an image file to the current PPT slide.",
        "ppt",
        "ppt_load_image",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT image element would be added",
    )
    registry.register_adapter_action(
        "ppt.element.add_video",
        "Add a video file to the current PPT slide as a video actor.",
        "ppt",
        "ppt_add_video_element",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT video element would be added",
    )
    registry.register_adapter_action(
        "ppt.element.add_shape",
        "Add a shape element to the current PPT slide.",
        "ppt",
        "ppt_add_shape_element",
        params_schema=schema_object(
            {
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "fill": {"type": "string"},
                "stroke": {"type": "string"},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT shape element would be added",
    )
    registry.register_adapter_action(
        "ppt.element.add_chart",
        "Add a chart element to the current PPT slide.",
        "ppt",
        "ppt_add_chart_element",
        params_schema=schema_object(
            {
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "chart_type": {"type": "string"},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT chart element would be added",
    )
    registry.register_adapter_action(
        "ppt.element.delete",
        "Delete an editable element from the current PPT deck.",
        "ppt",
        "ppt_delete_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element would be deleted",
    )
    registry.register_adapter_action(
        "ppt.element.remove",
        "Remove an editable element from the current PPT deck.",
        "ppt",
        "ppt_delete_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element would be removed",
    )
    registry.register_adapter_action(
        "ppt.element.duplicate",
        "Duplicate an editable PPT element on its slide.",
        "ppt",
        "ppt_duplicate_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element would be duplicated",
    )
    registry.register_adapter_action(
        "ppt.element.z_order",
        "Move an editable PPT element forward/backward or to front/back.",
        "ppt",
        "ppt_set_element_z_order",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "mode": {"type": "string", "enum": ["front", "back", "forward", "backward"]},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element layer order would be changed",
    )
    registry.register_adapter_action(
        "ppt.element.align",
        "Align an editable PPT element to the slide bounds.",
        "ppt",
        "ppt_align_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "horizontal": {"type": "string", "enum": ["", "left", "center", "right"]},
                "vertical": {"type": "string", "enum": ["", "top", "middle", "bottom"]},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element would be aligned",
    )
    registry.register_adapter_action(
        "ppt.element.arrange",
        "Arrange an editable PPT element by z-order and optional slide alignment.",
        "ppt",
        "ppt_arrange_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "mode": {"type": "string", "enum": ["", "front", "back", "forward", "backward"]},
                "horizontal": {"type": "string", "enum": ["", "left", "center", "right"]},
                "vertical": {"type": "string", "enum": ["", "top", "middle", "bottom"]},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element arrangement would be changed",
    )
    registry.register_adapter_action(
        "ppt.element.update",
        "Update an editable PPT element's text, layout, visibility, style, or metadata.",
        "ppt",
        "ppt_update_element",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "name": {"type": "string"},
                "text": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "rotation": {"type": "number"},
                "opacity": {"type": "number", "minimum": 0, "maximum": 1},
                "visible": {"type": "boolean"},
                "style": {"type": "object", "additionalProperties": True},
                "animation": {"type": "object", "additionalProperties": True},
                "metadata": {"type": "object", "additionalProperties": True},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element would be updated",
    )
    registry.register_adapter_action(
        "ppt.element.animation.set",
        "Set a PPT element animation timing/effect for AI-editable presentation motion.",
        "ppt",
        "ppt_set_element_animation",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "in_animation": {"type": "string"},
                "out_animation": {"type": "string"},
                "trigger": {"type": "string"},
                "start_ms": {"type": "integer", "minimum": 0},
                "duration_ms": {"type": "integer", "minimum": 1},
                "click_index": {"type": "integer", "minimum": 0},
                "easing": {"type": "string"},
                "motion_x": {"type": "number", "minimum": -1, "maximum": 1},
                "motion_y": {"type": "number", "minimum": -1, "maximum": 1},
                "scale": {"type": "number", "minimum": 0.1, "maximum": 4},
            },
            required=("element_id",),
        ),
        required=("element_id",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT element animation would be updated",
    )
    registry.register_adapter_action(
        "ppt.animation_lanes.list",
        "List animation timing-lane rows for the current or specified PPT slide.",
        "ppt",
        "ppt_animation_lanes_list",
        params_schema=schema_object({"slide_id": {"type": "string"}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="PPT animation timing lanes would be listed",
    )
    registry.register_adapter_action(
        "ppt.timeline.select_slide",
        "Select a PPT slide on the presentation timeline.",
        "ppt",
        "ppt_timeline_select_slide",
        params_schema=schema_object({"slide_id": {"type": "string"}}, required=("slide_id",)),
        required=("slide_id",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ui",
        dry_summary="PPT timeline slide would be selected",
    )
    registry.register_adapter_action(
        "ppt.timeline.set_playhead",
        "Set the PPT timeline playhead by absolute time or slide-local time.",
        "ppt",
        "ppt_timeline_set_playhead",
        params_schema=schema_object(
            {
                "time_ms": {"type": "integer", "minimum": 0},
                "slide_id": {"type": "string"},
                "local_ms": {"type": "integer", "minimum": 0},
            },
        ),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ui",
        dry_summary="PPT timeline playhead would be moved",
    )
    registry.register_adapter_action(
        "ppt.timeline.play_preview",
        "Play, pause, stop, or toggle the PPT timeline preview.",
        "ppt",
        "ppt_timeline_play_preview",
        params_schema=schema_object({"mode": {"type": "string", "enum": ["toggle", "play", "pause", "stop", "reset"]}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ui",
        dry_summary="PPT timeline preview playback would be controlled",
    )
    registry.register_adapter_action(
        "ppt.table.data.set",
        "Set editable table cell data. Cells may contain text, numbers, or formulas such as =A2+B2.",
        "ppt",
        "ppt_set_table_data",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "cells": {
                    "type": "array",
                    "items": {"type": "array"},
                },
                "header": {"type": "boolean"},
            },
            required=("element_id", "cells"),
        ),
        required=("element_id", "cells"),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT table data would be updated",
    )
    registry.register_adapter_action(
        "ppt.chart.data.set",
        "Set editable chart labels and values. Values may contain numbers or formulas.",
        "ppt",
        "ppt_set_chart_data",
        params_schema=schema_object(
            {
                "element_id": {"type": "string"},
                "slide_id": {"type": "string"},
                "labels": {"type": "array"},
                "values": {"type": "array"},
                "chart_type": {"type": "string"},
            },
            required=("element_id", "labels", "values"),
        ),
        required=("element_id", "labels", "values"),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="PPT chart data would be updated",
    )
    registry.register_adapter_action(
        "ppt.summary",
        "Build a summary of the current timeline-to-PPT draft deck.",
        "ppt",
        "ppt_summary",
        params_schema=schema_object({"max_slides": {"type": "integer", "minimum": 1}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="timeline PPT summary would be generated",
    )
    registry.register_adapter_action(
        "ppt.editor.open",
        "Open the user PPT generator window.",
        "ppt",
        "ppt_open_generator",
        params_schema=schema_object({"import_timeline": {"type": "boolean"}}),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ui",
        dry_summary="PPT generator window would be opened",
    )
    registry.register_adapter_action(
        "ppt.timeline.export",
        "Export the current editor timeline as a draft PPTX deck.",
        "ppt",
        "ppt_export_timeline",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "title": {"type": "string"},
                "max_slides": {"type": "integer", "minimum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current timeline would be exported as a PPTX deck",
    )
    registry.register_adapter_action(
        "ppt.timeline.export_pdf",
        "Export the current editor timeline as a draft PDF presentation.",
        "ppt",
        "ppt_export_timeline_pdf",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "title": {"type": "string"},
                "max_slides": {"type": "integer", "minimum": 1},
                "backend": {"type": "string", "enum": ["auto", "libreoffice", "powerpoint", "powerpoint_com"]},
                "timeout_sec": {"type": "integer", "minimum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current timeline would be exported as a PDF presentation",
    )
    registry.register_adapter_action(
        "ppt.timeline.export_video",
        "Export the current editor timeline as an MP4 presentation video.",
        "ppt",
        "ppt_export_timeline_video",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "title": {"type": "string"},
                "max_slides": {"type": "integer", "minimum": 1},
                "fps": {"type": "integer", "minimum": 1, "maximum": 120},
                "width": {"type": "integer", "minimum": 16},
                "height": {"type": "integer", "minimum": 16},
                "audio_path": {"type": "string"},
                "audio_bitrate": {"type": "string"},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=False,
        requires_owner=True,
        changed=False,
        async_kind="ppt",
        dry_summary="current timeline would be exported as an MP4 presentation video",
    )
    registry.register_adapter_action(
        "ppt.asset.add",
        "Add a media-pool/editor asset to the current PPT slide as an editable PPT actor.",
        "ppt",
        "ppt_add_media_asset",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "kind": {"type": "string"},
            },
            required=("path",),
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="media asset would be added to the PPT slide",
    )
    registry.register_adapter_action(
        "ppt.image.load",
        "Load an image into the current PPT slide or replace an existing image/image placeholder element.",
        "ppt",
        "ppt_load_image",
        params_schema=schema_object(
            {
                "path": {"type": "string"},
                "slide_id": {"type": "string"},
                "element_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
            required=("path",),
        ),
        required=("path",),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="image would be loaded into the PPT slide",
    )
    registry.register_adapter_action(
        "ppt.timeline_clip.add",
        "Add an editor timeline clip to the current PPT slide as a video actor.",
        "ppt",
        "ppt_add_timeline_clip",
        params_schema=schema_object(
            {
                "track_id": {"type": "integer"},
                "clip_id": {"type": "integer"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
            required=("track_id", "clip_id"),
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="timeline clip would be added to the PPT slide",
    )
    registry.register_adapter_action(
        "ppt.timeline_clip.still.add",
        "Extract a still image from the selected/current editor timeline clip and add it to the current PPT slide.",
        "ppt",
        "ppt_add_timeline_clip_still",
        params_schema=schema_object(
            {
                "track_id": {"type": "integer"},
                "clip_id": {"type": "integer"},
                "slide_id": {"type": "string"},
                "source_ms": {"type": "integer", "minimum": 0},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
            },
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="selected/current timeline clip would be captured as a PPT image",
    )
    registry.register_adapter_action(
        "ppt.typography.add",
        "Add typography text to the current PPT slide as an editable PPT typography actor.",
        "ppt",
        "ppt_add_typography",
        params_schema=schema_object(
            {
                "text": {"type": "string"},
                "slide_id": {"type": "string"},
                "x": {"type": "number", "minimum": 0, "maximum": 1},
                "y": {"type": "number", "minimum": 0, "maximum": 1},
                "w": {"type": "number", "minimum": 0, "maximum": 1},
                "h": {"type": "number", "minimum": 0, "maximum": 1},
                "font_size": {"type": "integer", "minimum": 8},
                "color": {"type": "string"},
            },
            required=("text",),
        ),
        mutating=True,
        requires_owner=True,
        changed=True,
        async_kind="ui",
        dry_summary="typography actor would be added to the PPT slide",
    )


__all__ = ["register_ppt_actions"]
