from __future__ import annotations

AUDIO_TOOL_DOCK_ICON_WIDTH = 300
AUDIO_TOOL_DOCK_ICON_HEIGHT = 64
AUDIO_TOOL_DOCK_BUTTON_MIN_HEIGHT = 70
AUDIO_TOOL_DOCK_BUTTON_MAX_HEIGHT = 72
AUDIO_TOOL_DOCK_BUTTON_RADIUS = 7


__all__ = [
    "AUDIO_TOOL_DOCK_BUTTON_MAX_HEIGHT",
    "AUDIO_TOOL_DOCK_BUTTON_MIN_HEIGHT",
    "AUDIO_TOOL_DOCK_BUTTON_RADIUS",
    "AUDIO_TOOL_DOCK_ICON_HEIGHT",
    "AUDIO_TOOL_DOCK_ICON_WIDTH",
]
