"""Automation plan for release-blocking evidence collection.

This module deliberately automates promotion, validation, and QA refresh.  It
does not fabricate cursor events, AI prompts, transcripts, or platform proof.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping


DEFAULT_OUT_DIR = Path("debugCapture/release_evidence_automation")


def _python_command(root: Path) -> str:
    local = root / ".venv" / "Scripts" / "python.exe"
    return str(local if local.exists() else Path("python"))


def _ps_quote(value: str | Path) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _file_count(path: Path, pattern: str) -> int:
    if not path.exists():
        return 0
    return len([row for row in path.glob(pattern) if row.is_file()])


def _filled_sidecar_templates(path: Path) -> int:
    count = 0
    if not path.exists():
        return 0
    for template in path.glob("*.cursor.template.json"):
        try:
            payload = json.loads(template.read_text(encoding="utf-8-sig"))
        except Exception:
            continue
        events = payload.get("events")
        if isinstance(events, list) and events:
            count += 1
    return count


def _filled_ai_templates(path: Path) -> int:
    count = 0
    if not path.exists():
        return 0
    for template in path.glob("*.template.json"):
        try:
            payload = json.loads(template.read_text(encoding="utf-8-sig"))
        except Exception:
            continue
        case = payload.get("manifest_case")
        if not isinstance(case, Mapping):
            continue
        if str(case.get("prompt") or "").strip() and str(case.get("transcript_path") or "").strip():
            count += 1
    return count


def _write_promote_script(root: Path, out_dir: Path) -> Path:
    script = out_dir / "promote_filled_release_evidence.ps1"
    python = _python_command(root)
    sidecar_dir = root / "debugCapture" / "release_evidence_sprint" / "screenstudio_sidecar_templates"
    ai_dir = root / "debugCapture" / "release_evidence_sprint" / "ai_edit_templates"
    lines = [
        "# Generated by tools/qa_release_evidence_automation.py",
        "# Promotes only filled real-evidence templates, then refreshes QA reports.",
        "$ErrorActionPreference = 'Stop'",
        f"$Python = {_ps_quote(python)}",
        f"Set-Location {_ps_quote(root)}",
        "",
        "Write-Host 'Promoting filled Screen Studio cursor sidecar templates...'",
        "& $Python 'tools/promote_screenstudio_sidecar_templates.py' "
        f"--template-dir {_ps_quote(sidecar_dir)} --register --recursive",
        "",
        "Write-Host 'Registering filled AI edit real-case templates...'",
        "& $Python 'tools/register_ai_edit_corpus_templates.py' "
        f"--template-dir {_ps_quote(ai_dir)} --overwrite --recursive",
        "",
        "Write-Host 'Refreshing release QA reports...'",
        "& $Python 'tools/qa_screenstudio_real_recording_corpus.py' --out 'debugCapture/screenstudio_real_recording_corpus_qa.json'",
        "& $Python 'tools/qa_ai_edit_corpus_quality.py' --use-provider --provider-timeout 30 --provider-retries 0 --out 'debugCapture/ai_edit_corpus_quality_qa.json'",
        "& $Python 'tools/qa_broadcast_platform_e2e.py' --out 'debugCapture/broadcast_platform_e2e_qa.json'",
        "& $Python 'tools/qa_broadcast_release_readiness.py' --out 'debugCapture/broadcast_release_readiness_qa.json'",
        "& $Python 'tools/qa_final_product_readiness.py' --out 'debugCapture/final_product_readiness_qa.json'",
        "",
        "Write-Host 'Evidence promotion and QA refresh finished.'",
        "",
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    script.write_text("\n".join(lines), encoding="utf-8-sig")
    return script


def _write_refresh_script(root: Path, out_dir: Path) -> Path:
    script = out_dir / "refresh_release_evidence_status.ps1"
    python = _python_command(root)
    lines = [
        "# Generated by tools/qa_release_evidence_automation.py",
        "# Refreshes reports only; it does not promote or write evidence.",
        "$ErrorActionPreference = 'Continue'",
        f"$Python = {_ps_quote(python)}",
        f"Set-Location {_ps_quote(root)}",
        "",
        "& $Python 'tools/qa_screenstudio_real_recording_corpus.py' --out 'debugCapture/screenstudio_real_recording_corpus_qa.json'",
        "& $Python 'tools/qa_ai_edit_corpus_quality.py' --out 'debugCapture/ai_edit_corpus_quality_qa.json'",
        "& $Python 'tools/qa_broadcast_platform_e2e.py' --out 'debugCapture/broadcast_platform_e2e_qa.json'",
        "& $Python 'tools/qa_broadcast_release_readiness.py' --out 'debugCapture/broadcast_release_readiness_qa.json'",
        "& $Python 'tools/qa_final_product_readiness.py' --out 'debugCapture/final_product_readiness_qa.json'",
        "",
        "Write-Host 'Release evidence status refreshed.'",
        "",
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    script.write_text("\n".join(lines), encoding="utf-8-sig")
    return script


def build_release_evidence_automation_report(
    root: str | Path = ".",
    *,
    out_dir: str | Path = DEFAULT_OUT_DIR,
    write_files: bool = False,
) -> dict[str, Any]:
    """Return the safe automation boundary for remaining release evidence."""

    root_path = Path(root).resolve()
    out_path = Path(out_dir)
    if not out_path.is_absolute():
        out_path = root_path / out_path

    final_report = _load_json(root_path / "debugCapture" / "final_product_readiness_qa.json")
    screen_report = _load_json(root_path / "debugCapture" / "screenstudio_real_recording_corpus_qa.json")
    ai_report = _load_json(root_path / "debugCapture" / "ai_edit_corpus_quality_qa.json")
    broadcast_report = _load_json(root_path / "debugCapture" / "broadcast_release_readiness_qa.json")
    sprint = _load_json(root_path / "debugCapture" / "release_evidence_sprint_qa.json")
    automated_corpus = _load_json(
        root_path / "debugCapture" / "release_evidence_automation" / "automated_release_evidence_corpus.json"
    )

    sprint_out = Path(str(sprint.get("out_dir") or root_path / "debugCapture" / "release_evidence_sprint"))
    if not sprint_out.is_absolute():
        sprint_out = root_path / sprint_out
    sidecar_dir = sprint_out / "screenstudio_sidecar_templates"
    ai_dir = sprint_out / "ai_edit_templates"

    screen_summary = screen_report.get("summary") if isinstance(screen_report.get("summary"), Mapping) else {}
    ai_summary = ai_report.get("summary") if isinstance(ai_report.get("summary"), Mapping) else {}
    broadcast_summary = broadcast_report.get("summary") if isinstance(broadcast_report.get("summary"), Mapping) else {}
    automated_summary = automated_corpus.get("summary") if isinstance(automated_corpus.get("summary"), Mapping) else {}

    sidecar_templates = _file_count(sidecar_dir, "*.cursor.template.json")
    sidecar_filled = _filled_sidecar_templates(sidecar_dir)
    ai_templates = _file_count(ai_dir, "*.template.json")
    ai_filled = _filled_ai_templates(ai_dir)
    platform_pending = _safe_int(broadcast_summary.get("sale_blocking"), 1)

    scripts: dict[str, str] = {}
    if write_files:
        promote_script = _write_promote_script(root_path, out_path)
        refresh_script = _write_refresh_script(root_path, out_path)
        scripts = {
            "promote_filled_release_evidence": str(promote_script),
            "refresh_release_evidence_status": str(refresh_script),
        }

    promotion_ready = bool(sidecar_filled or ai_filled)
    automation_ready = bool(sidecar_templates >= 1 and ai_templates >= 1 and scripts if write_files else sidecar_templates >= 1 and ai_templates >= 1)

    blockers: list[str] = []
    if sidecar_filled <= 0 and _safe_int(screen_summary.get("interaction_ready"), 0) < _safe_int(screen_summary.get("target_min"), 20):
        blockers.append("needs_filled_real_cursor_sidecar_templates_or_live_capture")
    if ai_filled <= 0 and _safe_int(ai_summary.get("real_cases"), 0) < _safe_int(ai_summary.get("min_real_cases"), 20):
        blockers.append("needs_filled_real_ai_case_templates")
    if not bool(broadcast_report.get("commercial_ready")):
        blockers.append("needs_redacted_real_platform_evidence")

    return {
        "ok": True,
        "kind": "release_evidence_automation",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "write_files": bool(write_files),
        "automation_ready": automation_ready,
        "promotion_ready_now": promotion_ready,
        "claim_unblocked_by_automation": False,
        "summary": {
            "final_score": _safe_int(final_report.get("score"), 0),
            "final_release_ready": bool(final_report.get("release_ready")),
            "screenstudio_valid_files": _safe_int(screen_summary.get("valid_files"), 0),
            "screenstudio_interaction_ready": _safe_int(screen_summary.get("interaction_ready"), 0),
            "screenstudio_target": _safe_int(screen_summary.get("target_min"), 20),
            "sidecar_templates": sidecar_templates,
            "sidecar_templates_filled": sidecar_filled,
            "ai_real_cases": _safe_int(ai_summary.get("real_cases"), 0),
            "ai_target": _safe_int(ai_summary.get("min_real_cases"), 20),
            "ai_templates": ai_templates,
            "ai_templates_filled": ai_filled,
            "broadcast_sale_blocking": platform_pending,
            "automated_corpus_present": bool(automated_corpus),
            "automated_corpus_screenstudio_ok": _safe_int(automated_summary.get("screenstudio_ok"), 0),
            "automated_corpus_ai_ok": _safe_int(automated_summary.get("ai_ok"), 0),
        },
        "automated_corpus": {
            "present": bool(automated_corpus),
            "report_path": str(root_path / "debugCapture" / "release_evidence_automation" / "automated_release_evidence_corpus.json")
            if automated_corpus
            else "",
            "provenance": str(automated_corpus.get("provenance") or ""),
            "counts_as_human_user_evidence": bool(automated_corpus.get("counts_as_human_user_evidence", True))
            if automated_corpus
            else False,
            "summary": dict(automated_summary),
        },
        "automation_paths": {
            "screenstudio": {
                "status": "partially_automated",
                "automatic": [
                    "new TigerCapture recordings write cursor sidecars at record time",
                    "filled .cursor.template.json files can be bulk-promoted and registered",
                    "automation-generated local MP4/sidecar corpora can be built for repeatable product QA with provenance",
                    "QA/final readiness refresh can run without more user clicks",
                ],
                "not_safe_to_fabricate": [
                    "old video files cannot prove click/drag/hotkey intent without captured or reviewed events",
                    "example template events must not be copied into counted sidecars",
                    "automation-generated corpora must not be marketed as human user recordings",
                ],
            },
            "ai_edit": {
                "status": "automated_after_real_inputs",
                "automatic": [
                    "filled AI templates are batch-registered through validation",
                    "automation-generated transcript/prompt cases can exercise local plan QA with provenance",
                    "real transcripts are copied into the corpus and provider QA can rerun",
                ],
                "not_safe_to_fabricate": [
                    "20 real cases cannot be made by duplicating one transcript or placeholder prompts",
                    "automation-generated corpora do not prove real human editing demand",
                    "provider fallback does not count as direct smart-edit evidence",
                ],
            },
            "broadcast": {
                "status": "registration_automated_platform_session_external",
                "automatic": [
                    "redacted platform evidence can be registered through action/CLI",
                    "broadcast QA and final readiness refresh are scripted",
                ],
                "not_safe_to_fabricate": [
                    "YouTube/Twitch/Discord receipt must come from an actual private platform session",
                    "stream keys or account tokens must never be stored in evidence",
                ],
            },
        },
        "scripts": scripts,
        "blockers": blockers,
    }
