"""Ai VideoEditorWindow delegate bindings."""
from __future__ import annotations

from app.video_editor_delegate_binding import bind_imported_delegate_methods
from app import video_editor_ai_workflow as _ai_workflow

_BINDINGS = (
    ('_apply_ai_script_edit_plan', 'app.video_editor_ai_workflow', '_apply_ai_script_edit_plan', False),
    ('_build_ai_command_dock', 'app.video_editor_ai_command_controller', 'build_ai_command_dock', False),
    ('_toggle_ai_command_dock', 'app.video_editor_ai_command_controller', 'toggle_ai_command_dock', False),
    ('_show_ai_command_dock', 'app.video_editor_ai_command_controller', 'show_ai_command_dock', False),
    ('_hide_ai_command_dock', 'app.video_editor_ai_command_controller', 'hide_ai_command_dock', False),
    ('_toggle_ai_command_popout', 'app.video_editor_ai_command_controller', 'toggle_ai_command_popout', False),
    ('_restore_ai_command_dock_from_popout', 'app.video_editor_ai_command_controller', 'restore_ai_command_dock_from_popout', False),
    ('_ai_command_format_srt_ms', 'app.video_editor_ai_workflow', '_ai_command_format_srt_ms', True),
    ('_claude_mcp_add_args', 'app.video_editor_ai_workflow', '_claude_mcp_add_args', False),
    ('_find_claude_cli', 'app.video_editor_ai_workflow', '_find_claude_cli', False),
    ('_launch_claude_code_terminal', 'app.video_editor_ai_workflow', '_launch_claude_code_terminal', False),
    ('_open_local_llm_provider_setup_dialog', 'app.video_editor_ai_workflow', '_open_local_llm_provider_setup_dialog', False),
    ('_quote_powershell_literal', 'app.video_editor_ai_workflow', '_quote_powershell_literal', False),
    ('_refresh_ai_command_provider_status', 'app.video_editor_ai_workflow', '_refresh_ai_command_provider_status', False),
    ('_remove_ai_script_preview_markers', 'app.video_editor_ai_workflow', '_remove_ai_script_preview_markers', False),
    ('_sync_ai_script_preview_markers', 'app.video_editor_ai_workflow', '_sync_ai_script_preview_markers', False),
    ('_write_claude_code_terminal_files', 'app.video_editor_ai_workflow', '_write_claude_code_terminal_files', False),
)

_AI_WORKFLOW_NAMES = (
    '_open_ai_command_review_panel',
    '_prime_ai_review_panel',
    '_open_ai_script_review_dialog',
    '_current_ai_command_action_plan',
    '_ensure_python_action_registry',
    '_run_review_scenario',
    '_build_ai_command_action_plan_payload',
    '_format_ai_action_plan_text',
    '_open_ai_action_review_dialog',
    '_execute_ai_command_action_plan',
    '_clear_ai_action_review_dialog',
    '_clear_ai_review_dialog',
    '_ai_command_set_status',
    '_ai_command_append_chat',
    '_ai_command_selected_provider_name',
    '_on_ai_command_provider_changed',
    '_selected_ai_command_provider_id',
    '_open_ai_provider_setup_dialog',
    '_open_ai_provider_setup_for_id',
    '_refresh_ai_script_edit_provider_status',
    '_show_ai_provider_instructions',
    '_open_claude_provider_setup_dialog',
    '_open_claude_mcp_progress_dialog',
    '_claude_mcp_log',
    '_claude_mcp_state',
    '_start_claude_mcp_auto_connect',
    '_start_claude_mcp_status_check',
    '_start_claude_mcp_process',
    '_claude_mcp_read_output',
    '_claude_mcp_process_error',
    '_claude_mcp_process_finished',
    '_claude_mcp_finish_ui',
    '_claude_mcp_start_close_attention',
    '_claude_mcp_stop_close_attention',
    '_claude_mcp_cancel',
    '_open_qwen_provider_setup_dialog',
    '_start_default_free_ai_install',
    '_open_qwen_install_progress_dialog',
    '_qwen_install_log',
    '_qwen_install_state',
    '_qwen_install_cached_model_path',
    '_qwen_install_runner_candidates',
    '_qwen_install_find_runner',
    '_qwen_install_begin',
    '_qwen_install_start_winget',
    '_qwen_install_winget_finished',
    '_qwen_install_start_server_after_install',
    '_qwen_install_start_server',
    '_qwen_install_read_output',
    '_qwen_install_server_output',
    '_qwen_install_process_error',
    '_qwen_install_server_finished',
    '_shutdown_qwen_local_processes',
    '_qwen_install_probe_server',
    '_qwen_install_finish_ui',
    '_qwen_install_start_close_attention',
    '_qwen_install_stop_close_attention',
    '_qwen_install_cancel',
    '_save_qwen_endpoint_from_dialog',
    '_choose_qwen_model_path',
    '_ai_command_transcript_text',
    '_ai_command_prompt_only_plan',
    '_handle_ai_command_status_prompt',
    '_generate_ai_command_plan',
    '_ensure_ai_script_edit_panel',
    '_open_ai_script_edit_panel',
    '_ai_project_snapshot',
    '_log_ai_script_action',
    '_validate_ai_script_edit_plan',
    '_ensure_automation_registry',
    'automation_command_specs',
    'automation_execute_command',
    'automation_bridge_handle',
    'automation_mcp_handle',
    '_on_ai_script_edit_plan_generated',
    '_current_ai_script_edit_plan',
    '_apply_ai_script_edit_selected',
    '_apply_ai_script_edit_all',
    '_apply_ai_script_edit_cuts',
    '_apply_ai_script_subtitles',
    '_apply_ai_script_markers',
    '_ai_script_auto_zoom_sidecars',
    '_apply_ai_script_auto_suggestions',
    '_first_ai_script_video_start_ms',
    '_sync_ai_script_applied_cut_markers',
    '_store_ai_script_edit_payload',
)


def install_ai_delegates(VideoEditorWindow) -> None:
    bind_imported_delegate_methods(VideoEditorWindow, _BINDINGS)
    for name in _AI_WORKFLOW_NAMES:
        setattr(VideoEditorWindow, name, getattr(_ai_workflow, name))
