"""Ppt VideoEditorWindow delegate bindings."""
from __future__ import annotations

from app.video_editor_delegate_binding import bind_imported_delegate_methods

_BINDINGS = (
    ('_open_ppt_generator', 'app.video_editor_ppt_workflow', 'open_ppt_generator', False),
    ('_ppt_project_create', 'app.video_editor_ppt_workflow', 'create_ppt_project', False),
    ('_ppt_deck_from_prompt', 'app.video_editor_ppt_workflow', 'create_ppt_deck_from_prompt', False),
    ('_ppt_deck_from_timeline', 'app.video_editor_ppt_workflow', 'create_ppt_deck_from_timeline', False),
    ('_ppt_project_open', 'app.video_editor_ppt_workflow', 'open_ppt_project', False),
    ('_ppt_project_save', 'app.video_editor_ppt_workflow', 'save_ppt_project', False),
    ('_ppt_project_save_as', 'app.video_editor_ppt_workflow', 'save_ppt_project_as', False),
    ('_export_timeline_pptx', 'app.video_editor_ppt_workflow', 'export_timeline_pptx', False),
    ('_export_timeline_pdf', 'app.video_editor_ppt_workflow', 'export_timeline_pdf', False),
    ('_export_timeline_video', 'app.video_editor_ppt_workflow', 'export_timeline_video', False),
    ('_ppt_export_deck_pptx', 'app.video_editor_ppt_workflow', 'export_ppt_deck_pptx', False),
    ('_ppt_export_deck_pdf', 'app.video_editor_ppt_workflow', 'export_ppt_deck_pdf', False),
    ('_ppt_export_deck_video', 'app.video_editor_ppt_workflow', 'export_ppt_deck_video', False),
    ('_ppt_add_media_asset', 'app.video_editor_ppt_workflow', 'add_media_asset_to_ppt', False),
    ('_ppt_add_text_element', 'app.video_editor_ppt_workflow', 'add_text_element_to_ppt', False),
    ('_ppt_add_shape_element', 'app.video_editor_ppt_workflow', 'add_shape_element_to_ppt', False),
    ('_ppt_add_chart_element', 'app.video_editor_ppt_workflow', 'add_chart_element_to_ppt', False),
    ('_ppt_load_image', 'app.video_editor_ppt_workflow', 'load_image_to_ppt', False),
    ('_ppt_add_timeline_clip', 'app.video_editor_ppt_workflow', 'add_timeline_clip_to_ppt', False),
    ('_ppt_add_timeline_clip_still', 'app.video_editor_ppt_workflow', 'add_timeline_clip_still_to_ppt', False),
    ('_ppt_add_typography', 'app.video_editor_ppt_workflow', 'add_typography_to_ppt', False),
    ('_ppt_apply_template', 'app.video_editor_ppt_workflow', 'apply_template_to_ppt', False),
    ('_ppt_snapshot', 'app.video_editor_ppt_workflow', 'snapshot_ppt', False),
    ('_ppt_validate', 'app.video_editor_ppt_workflow', 'validate_ppt_deck', False),
    ('_ppt_import_pptx', 'app.video_editor_ppt_workflow', 'import_pptx_to_ppt', False),
    ('_ppt_generate_actor_posters', 'app.video_editor_ppt_workflow', 'generate_ppt_actor_posters', False),
    ('_ppt_history_status', 'app.video_editor_ppt_workflow', 'ppt_history_status', False),
    ('_ppt_undo', 'app.video_editor_ppt_workflow', 'undo_ppt_edit', False),
    ('_ppt_redo', 'app.video_editor_ppt_workflow', 'redo_ppt_edit', False),
    ('_ppt_autosave', 'app.video_editor_ppt_workflow', 'autosave_ppt', False),
    ('_ppt_recovery_list', 'app.video_editor_ppt_workflow', 'list_ppt_recovery_candidates', False),
    ('_ppt_recovery_open', 'app.video_editor_ppt_workflow', 'open_ppt_recovery_copy', False),
    ('_ppt_recovery_delete', 'app.video_editor_ppt_workflow', 'delete_ppt_recovery_copy', False),
    ('_ppt_media_pool_list', 'app.video_editor_ppt_workflow', 'list_ppt_media_pool', False),
    ('_ppt_media_pool_add', 'app.video_editor_ppt_workflow', 'add_ppt_media_pool_asset', False),
    ('_ppt_media_pool_insert', 'app.video_editor_ppt_workflow', 'insert_ppt_media_pool_asset', False),
    ('_ppt_media_pool_remove', 'app.video_editor_ppt_workflow', 'remove_ppt_media_pool_asset', False),
    ('_ppt_animation_lanes_list', 'app.video_editor_ppt_workflow', 'list_ppt_animation_lanes', False),
    ('_ppt_timeline_select_slide', 'app.video_editor_ppt_workflow', 'select_ppt_timeline_slide', False),
    ('_ppt_timeline_set_playhead', 'app.video_editor_ppt_workflow', 'set_ppt_timeline_playhead', False),
    ('_ppt_timeline_play_preview', 'app.video_editor_ppt_workflow', 'play_ppt_timeline_preview', False),
    ('_ppt_add_slide', 'app.video_editor_ppt_workflow', 'add_ppt_slide', False),
    ('_ppt_duplicate_slide', 'app.video_editor_ppt_workflow', 'duplicate_ppt_slide', False),
    ('_ppt_delete_slide', 'app.video_editor_ppt_workflow', 'delete_ppt_slide', False),
    ('_ppt_move_slide', 'app.video_editor_ppt_workflow', 'move_ppt_slide', False),
    ('_ppt_update_slide', 'app.video_editor_ppt_workflow', 'update_ppt_slide', False),
    ('_ppt_delete_element', 'app.video_editor_ppt_workflow', 'delete_ppt_element', False),
    ('_ppt_duplicate_element', 'app.video_editor_ppt_workflow', 'duplicate_ppt_element', False),
    ('_ppt_align_element', 'app.video_editor_ppt_workflow', 'align_ppt_element', False),
    ('_ppt_set_element_z_order', 'app.video_editor_ppt_workflow', 'set_ppt_element_z_order', False),
    ('_ppt_update_element', 'app.video_editor_ppt_workflow', 'update_ppt_element', False),
    ('_ppt_set_element_animation', 'app.video_editor_ppt_workflow', 'set_ppt_element_animation', False),
    ('_ppt_set_table_data', 'app.video_editor_ppt_workflow', 'set_ppt_table_data', False),
    ('_ppt_set_chart_data', 'app.video_editor_ppt_workflow', 'set_ppt_chart_data', False),
)


def install_ppt_delegates(VideoEditorWindow) -> None:
    bind_imported_delegate_methods(VideoEditorWindow, _BINDINGS)
