"""Core VideoEditorWindow delegate bindings."""
from __future__ import annotations

from app.video_editor_delegate_binding import bind_imported_delegate_methods

_BINDINGS = (
    ('_build_ui', 'app.video_editor_ui_builder', 'build_video_editor_ui', False),
    ('_yield_startup_ui', 'app.video_editor_lifecycle_workflow', '_yield_startup_ui', False),
    ('_record_editor_action', 'app.video_editor_lifecycle_workflow', '_record_editor_action', False),
    ('closeEvent', 'app.video_editor_lifecycle_workflow', 'closeEvent', False),
    ('_make_section_header', 'app.video_editor_window_chrome_workflow', '_make_section_header', True),
    ('_make_command_menu_button', 'app.video_editor_window_chrome_workflow', '_make_command_menu_button', False),
    ('_install_lazy_action_menu', 'app.video_editor_window_chrome_workflow', '_install_lazy_action_menu', False),
    ('_install_lazy_menu_builder', 'app.video_editor_window_chrome_workflow', '_install_lazy_menu_builder', False),
    ('_refresh_command_bar_responsive', 'app.video_editor_command_palette_controller', '_refresh_command_bar_responsive', False),
    ('_compact_command_bar', 'app.video_editor_command_palette_controller', '_compact_command_bar', False),
    ('_make_collapsible_section_header', 'app.video_editor_window_chrome_workflow', '_make_collapsible_section_header', False),
    ('_show_existing_button_menu', 'app.video_editor_window_chrome_workflow', '_show_existing_button_menu', False),
    ('_install_icon_pulse', 'app.video_editor_window_chrome_workflow', '_install_icon_pulse', False),
    ('_pulse_icon_button', 'app.video_editor_window_chrome_workflow', '_pulse_icon_button', False),
    ('_set_timeline_palette_collapsed', 'app.video_editor_window_chrome_workflow', '_set_timeline_palette_collapsed', False),
    ('_flash_status', 'app.video_editor_window_chrome_workflow', '_flash_status', False),
    ('_toggle_timeline_popout', 'app.video_editor_window_chrome_workflow', '_toggle_timeline_popout', False),
    ('_on_timeline_popout_closed', 'app.video_editor_window_chrome_workflow', '_on_timeline_popout_closed', False),
    ('_apply_professional_ui_labels', 'app.video_editor_localization_controller', '_apply_professional_ui_labels', False),
    ('_build_language_menu', 'app.video_editor_localization_controller', '_build_language_menu', False),
    ('_scale_preview_to_fit', 'app.video_editor_window_geometry_workflow', '_scale_preview_to_fit', False),
    ('_preview_frame_rect_in_label', 'app.video_editor_window_geometry_workflow', '_preview_frame_rect_in_label', False),
    ('_sync_overlay_to_video_rect', 'app.video_editor_window_geometry_workflow', '_sync_overlay_to_video_rect', False),
    ('_sync_preview_gl_geometry', 'app.video_editor_window_geometry_workflow', '_sync_preview_gl_geometry', False),
    ('_begin_window_move_guard', 'app.video_editor_window_geometry_workflow', '_begin_window_move_guard', False),
    ('_end_window_move_guard', 'app.video_editor_window_geometry_workflow', '_end_window_move_guard', False),
    ('resizeEvent', 'app.video_editor_window_geometry_workflow', 'resizeEvent', False),
    ('moveEvent', 'app.video_editor_window_geometry_workflow', 'moveEvent', False),
    ('_language_display_name', 'app.video_editor_localization_controller', '_language_display_name', False),
    ('_on_language_picked', 'app.video_editor_localization_controller', '_on_language_picked', False),
    ('_on_media_pool_popout_closed', 'app.video_editor_popout_controller', 'on_media_pool_popout_closed', False),
    ('_on_section_popout_closed', 'app.video_editor_popout_controller', 'on_section_popout_closed', False),
    ('_on_subtitle_popout_closed', 'app.video_editor_popout_controller', 'on_subtitle_popout_closed', False),
    ('_on_workbench_popout_closed', 'app.video_editor_popout_controller', 'on_workbench_popout_closed', False),
    ('_open_command_palette', 'app.video_editor_command_palette_controller', '_open_command_palette', False),
    ('_refresh_collapsible_header_title', 'app.video_editor_localization_controller', '_refresh_collapsible_header_title', False),
    ('_refresh_language_button', 'app.video_editor_localization_controller', '_refresh_language_button', False),
    ('_refresh_localized_ui', 'app.video_editor_localization_controller', '_refresh_localized_ui', False),
    ('_refresh_main_dock_splitter_roles', 'app.video_editor_popout_controller', 'refresh_main_dock_splitter_roles', False),
    ('_refresh_top_project_breadcrumb', 'app.video_editor_localization_controller', '_refresh_top_project_breadcrumb', False),
    ('_refresh_workbench', 'app.video_editor_workbench_controller', 'refresh_workbench', False),
    ('_on_workbench_node_focused', 'app.video_editor_workbench_controller', '_on_workbench_node_focused', False),
    ('_set_collapsible_host_open', 'app.video_editor_section_chrome', 'set_collapsible_host_open', True),
    ('_toggle_media_pool_popout', 'app.video_editor_popout_controller', 'toggle_media_pool_popout', False),
    ('_make_side_dock_placeholder', 'app.video_editor_popout_controller', 'make_side_dock_placeholder_for_owner', False),
    ('_toggle_actor_library_popout', 'app.video_editor_popout_controller', 'toggle_actor_library_popout', False),
    ('_toggle_effects_library_popout', 'app.video_editor_popout_controller', 'toggle_effects_library_popout', False),
    ('_toggle_title_presets_popout', 'app.video_editor_popout_controller', 'toggle_title_presets_popout', False),
    ('_toggle_transitions_popout', 'app.video_editor_popout_controller', 'toggle_transitions_popout', False),
    ('_toggle_workflow_presets_popout', 'app.video_editor_popout_controller', 'toggle_workflow_presets_popout', False),
    ('_toggle_creator_assist_popout', 'app.video_editor_popout_controller', 'toggle_creator_assist_popout', False),
    ('_toggle_script_edit_popout', 'app.video_editor_popout_controller', 'toggle_script_edit_popout', False),
    ('_toggle_audio_workspace_popout', 'app.video_editor_popout_controller', 'toggle_audio_workspace_popout', False),
    ('_toggle_pip_popout', 'app.video_editor_popout_controller', 'toggle_pip_popout', False),
    ('_toggle_section_popout', 'app.video_editor_popout_controller', 'toggle_section_popout', False),
    ('_toggle_subtitle_popout', 'app.video_editor_popout_controller', 'toggle_subtitle_popout', False),
    ('_toggle_workbench_popout', 'app.video_editor_popout_controller', 'toggle_workbench_popout', False),
)


def install_core_delegates(VideoEditorWindow) -> None:
    bind_imported_delegate_methods(VideoEditorWindow, _BINDINGS)
