"""Audio Color VideoEditorWindow delegate bindings."""
from __future__ import annotations

from app.video_editor_delegate_binding import bind_imported_delegate_methods

_BINDINGS = (
    ('_next_clip_id', 'app.video_editor_audio_workspace_workflow', '_next_clip_id', False),
    ('_find_audio_track', 'app.video_editor_audio_workspace_workflow', '_find_audio_track', False),
    ('_find_audio_clip', 'app.video_editor_audio_workspace_workflow', '_find_audio_clip', False),
    ('_on_audio_track_changed', 'app.video_editor_audio_workspace_workflow', '_on_audio_track_changed', False),
    ('_on_audio_mixer_visibility_changed', 'app.video_editor_audio_workspace_workflow', '_on_audio_mixer_visibility_changed', False),
    ('_on_mixer_pan_changed', 'app.video_editor_audio_workspace_workflow', '_on_mixer_pan_changed', False),
    ('_on_mixer_mute_changed', 'app.video_editor_audio_workspace_workflow', '_on_mixer_mute_changed', False),
    ('_on_mixer_solo_changed', 'app.video_editor_audio_workspace_workflow', '_on_mixer_solo_changed', False),
    ('_populate_audio_track', 'app.video_editor_audio_workspace_workflow', '_populate_audio_track', False),
    ('_on_audio_clip_selection_changed', 'app.video_editor_audio_workspace_workflow', '_on_audio_clip_selection_changed', False),
    ('_open_sound_editor', 'app.video_editor_audio_workspace_workflow', '_open_sound_editor', False),
    ('_open_advanced_sound_lab', 'app.video_editor_audio_workspace_workflow', '_open_advanced_sound_lab', False),
    ('_audio_workspace_candidate', 'app.video_editor_audio_workspace_workflow', '_audio_workspace_candidate', False),
    ('_refresh_audio_workspace_panel', 'app.video_editor_audio_workspace_workflow', '_refresh_audio_workspace_panel', False),
    ('_open_selected_audio_workspace', 'app.video_editor_audio_workspace_workflow', '_open_selected_audio_workspace', False),
    ('_toggle_audio_workspace_mixer', 'app.video_editor_audio_workspace_workflow', '_toggle_audio_workspace_mixer', False),
    ('_toggle_audio_workspace_scopes', 'app.video_editor_audio_workspace_workflow', '_toggle_audio_workspace_scopes', False),
    ('_on_audio_volume_changed', 'app.video_editor_audio_workspace_workflow', '_on_audio_volume_changed', False),
    ('_on_workbench_sound_editor_changed', 'app.video_editor_audio_workspace_workflow', '_on_workbench_sound_editor_changed', False),
    ('_on_workbench_sound_editor_mixer_track_changed', 'app.video_editor_audio_workspace_workflow', '_on_workbench_sound_editor_mixer_track_changed', False),
    ('_on_workbench_music_lab_action_requested', 'app.video_editor_audio_workspace_workflow', '_on_workbench_music_lab_action_requested', False),
    ('_on_workbench_music_lab_selection_changed', 'app.video_editor_audio_workspace_workflow', '_on_workbench_music_lab_selection_changed', False),
    ('_on_audio_scopes_toggled', 'app.video_editor_audio_workspace_workflow', '_on_audio_scopes_toggled', False),
    ('_on_audio_mixer_toggled', 'app.video_editor_audio_workspace_workflow', '_on_audio_mixer_toggled', False),
    ('_on_mixer_fader_changed', 'app.video_editor_audio_workspace_workflow', '_on_mixer_fader_changed', False),
    ('_build_color_grading_panel', 'app.video_editor_color_panels', '_build_color_grading_panel', False),
    ('_build_color_inline_panel', 'app.video_editor_color_panels', '_build_color_inline_panel', False),
    ('_build_color_compact_palette_panel', 'app.video_editor_color_panels', '_build_color_compact_palette_panel', False),
    ('_build_color_reference_workbench_panel', 'app.video_editor_color_panels', '_build_color_reference_workbench_panel', False),
    ('parent_widget_for_color', 'app.video_editor_color_panels', 'parent_widget_for_color', False),
    ('_toggle_color_popout', 'app.video_editor_color_panels', '_toggle_color_popout', False),
    ('_toggle_color_scopes_popout', 'app.video_editor_color_panels', '_toggle_color_scopes_popout', False),
    ('_on_color_popout_closed', 'app.video_editor_color_panels', '_on_color_popout_closed', False),
    ('_on_color_scopes_popout_closed', 'app.video_editor_color_panels', '_on_color_scopes_popout_closed', False),
    ('_on_color_page_closed', 'app.video_editor_color_panels', '_on_color_page_closed', False),
    ('_disable_color_power_window_overlay', 'app.video_editor_color_panels', '_disable_color_power_window_overlay', False),
    ('_show_color_dock_page', 'app.video_editor_color_panels', '_show_color_dock_page', False),
    ('_open_color_page', 'app.video_editor_color_panels', '_open_color_page', False),
    ('_switch_page', 'app.video_editor_color_panels', '_switch_page', False),
    ('_close_color_page', 'app.video_editor_color_panels', '_close_color_page', False),
    ('_on_color_page_grade_changed', 'app.video_editor_color_panels', '_on_color_page_grade_changed', False),
    ('_sync_color_power_window_overlay', 'app.video_editor_color_panels', '_sync_color_power_window_overlay', False),
    ('_on_color_power_window_dragged', 'app.video_editor_color_panels', '_on_color_power_window_dragged', False),
    ('_active_color_grade', 'app.video_editor_color_panels', '_active_color_grade', False),
    ('_set_color_preview_compare_mode', 'app.video_editor_color_panels', '_set_color_preview_compare_mode', False),
    ('_load_lut_file', 'app.video_editor_color_panels', '_load_lut_file', False),
    ('_on_lut_strength_changed', 'app.video_editor_color_panels', '_on_lut_strength_changed', False),
    ('_clear_lut', 'app.video_editor_color_panels', '_clear_lut', False),
    ('_on_color_slider_changed', 'app.video_editor_color_panels', '_on_color_slider_changed', False),
    ('_on_color_wheel_changed', 'app.video_editor_color_panels', '_on_color_wheel_changed', False),
    ('_reset_color_wheel_region', 'app.video_editor_color_panels', '_reset_color_wheel_region', False),
    ('_sync_both_color_panels_except', 'app.video_editor_color_panels', '_sync_both_color_panels_except', False),
    ('_on_color_luma_changed', 'app.video_editor_color_panels', '_on_color_luma_changed', False),
    ('_on_hue_curve_changed', 'app.video_editor_color_panels', '_on_hue_curve_changed', False),
    ('_on_color_reset', 'app.video_editor_color_panels', '_on_color_reset', False),
    ('_on_color_preset_picked', 'app.video_editor_color_panels', '_on_color_preset_picked', False),
    ('_on_professional_color_preset_picked', 'app.video_editor_color_panels', '_on_professional_color_preset_picked', False),
    ('_update_wheel_readouts', 'app.video_editor_color_panels', '_update_wheel_readouts', False),
    ('_refresh_color_preset_btn_label', 'app.video_editor_color_panels', '_refresh_color_preset_btn_label', False),
    ('_build_color_preset_menu', 'app.video_editor_color_panels', '_build_color_preset_menu', False),
    ('_commit_color_preview_edit', 'app.video_editor_color_panels', '_commit_color_preview_edit', False),
    ('_compact_color_card_style', 'app.video_editor_color_panels', '_compact_color_card_style', True),
    ('_format_color_slider_label', 'app.video_editor_color_panels', '_format_color_slider_label', False),
    ('_load_lut_from_path', 'app.video_editor_color_panels', '_load_lut_from_path', False),
    ('_pulse_compact_color_card', 'app.video_editor_color_panels', '_pulse_compact_color_card', False),
    ('_pulse_compact_color_cards', 'app.video_editor_color_panels', '_pulse_compact_color_cards', False),
    ('_refresh_color_target_badge', 'app.video_editor_color_panels', '_refresh_color_target_badge', False),
    ('_set_color_reference_workspace_ratio', 'app.video_editor_color_panels', '_set_color_reference_workspace_ratio', False),
    ('_sync_color_compare_buttons', 'app.video_editor_color_panels', '_sync_color_compare_buttons', False),
    ('_sync_color_inline_panel', 'app.video_editor_color_panels', '_sync_color_inline_panel', False),
    ('_sync_color_panel', 'app.video_editor_color_panels', '_sync_color_panel', False),
    ('_update_color_dock_visibility', 'app.video_editor_color_panels', '_update_color_dock_visibility', False),
)


def install_audio_color_delegates(VideoEditorWindow) -> None:
    bind_imported_delegate_methods(VideoEditorWindow, _BINDINGS)
