"""Media Preview Export VideoEditorWindow delegate bindings."""
from __future__ import annotations

from app.video_editor_delegate_binding import bind_imported_delegate_methods
from app import video_editor_broadcast_workflow as _broadcast_workflow

_BINDINGS = (
    ('_add_timeline_media_from_mime', 'app.video_editor_media_import_controller', 'add_timeline_media_from_mime', False),
    ('_on_media_pool_item_added', 'app.video_editor_media_import_controller', 'on_media_pool_item_added', False),
    ('_on_media_pool_selection_changed', 'app.video_editor_media_import_controller', 'on_media_pool_selection_changed', False),
    ('_on_media_dropped_on_video_row', 'app.video_editor_media_import_controller', 'on_media_dropped_on_video_row', False),
    ('_on_media_dropped_on_audio_row', 'app.video_editor_media_import_controller', 'on_media_dropped_on_audio_row', False),
    ('eventFilter', 'app.video_editor_input_workflow', 'eventFilter', False),
    ('keyPressEvent', 'app.video_editor_input_workflow', 'keyPressEvent', False),
    ('dragEnterEvent', 'app.video_editor_input_workflow', 'dragEnterEvent', False),
    ('dragMoveEvent', 'app.video_editor_input_workflow', 'dragMoveEvent', False),
    ('_show_preview_context_menu', 'app.video_editor_input_workflow', '_show_preview_context_menu', False),
    ('_preview_has_renderable_content', 'app.video_editor_input_workflow', '_preview_has_renderable_content', False),
    ('_ensure_preview_pixmap_for_paint', 'app.video_editor_input_workflow', '_ensure_preview_pixmap_for_paint', False),
    ('_escape_timeline_context', 'app.video_editor_input_workflow', '_escape_timeline_context', False),
    ('_start_preview_transition_guard', 'app.video_editor_preview_recovery', 'start_preview_transition_guard', False),
    ('_preview_tab_guard_active', 'app.video_editor_preview_recovery', 'preview_tab_guard_active', False),
    ('_preview_black_recovery_active', 'app.video_editor_preview_recovery', 'preview_black_recovery_active', False),
    ('_pixmap_looks_like_blank_preview', 'app.video_editor_preview_recovery', 'pixmap_looks_like_blank_preview', True),
    ('_rgb_looks_like_blank_preview', 'app.video_editor_preview_recovery', 'rgb_looks_like_blank_preview', True),
    ('_pixmap_looks_like_black_frame', 'app.video_editor_preview_recovery', 'pixmap_looks_like_black_frame', True),
    ('_preview_recovery_source', 'app.video_editor_preview_recovery', 'preview_recovery_source', False),
    ('_preview_recovery_rgb', 'app.video_editor_preview_recovery', 'preview_recovery_rgb', False),
    ('_remember_good_preview_pixmap', 'app.video_editor_preview_recovery', 'remember_good_preview_pixmap', False),
    ('_restore_preview_if_tab_switch_blank', 'app.video_editor_preview_recovery', 'restore_preview_if_tab_switch_blank', False),
    ('_collect_nested_audio_preview_clips', 'app.video_editor_player_bridge', 'collect_nested_audio_preview_clips', False),
    ('_on_player_error', 'app.video_editor_player_bridge', '_on_player_error', False),
    ('_on_media_status', 'app.video_editor_player_bridge', '_on_media_status', False),
    ('_sync_nested_audio_preview_track', 'app.video_editor_player_bridge', 'sync_nested_audio_preview_track', False),
    ('_refresh_player_tracks', 'app.video_editor_player_bridge', 'refresh_player_tracks', False),
    ('_on_playback_state_changed', 'app.video_editor_player_bridge', 'on_playback_state_changed', False),
    ('_on_position_changed', 'app.video_editor_player_bridge', 'on_position_changed', False),
    ('_update_audio_level_meters', 'app.video_editor_player_bridge', 'update_audio_level_meters', False),
    ('_on_duration_changed', 'app.video_editor_player_bridge', 'on_duration_changed', False),
    ('_stage_ai_script_render_jobs', 'app.video_editor_render_queue_bridge', 'stage_ai_script_render_jobs', False),
    ('_queue_creator_assist_exports', 'app.video_editor_render_queue_bridge', 'queue_creator_assist_exports', False),
    ('_stage_creator_assist_render_jobs', 'app.video_editor_render_queue_bridge', 'stage_creator_assist_render_jobs', False),
    ('_toggle_render_queue_popout', 'app.video_editor_render_queue_bridge', 'toggle_render_queue_popout', False),
    ('_startup_template_status', 'app.video_editor_startup_template_controller', '_startup_template_status', False),
    ('_refresh_startup_template_ui', 'app.video_editor_startup_template_controller', '_refresh_startup_template_ui', False),
    ('show_startup_template_hint', 'app.video_editor_startup_template_controller', 'show_startup_template_hint', False),
    ('_startup_template_has_media_target', 'app.video_editor_startup_template_controller', '_startup_template_has_media_target', False),
    ('_startup_template_target_state', 'app.video_editor_startup_template_controller', '_startup_template_target_state', False),
    ('_startup_template_required_target_gap', 'app.video_editor_startup_template_controller', '_startup_template_required_target_gap', False),
    ('_startup_template_preset', 'app.video_editor_startup_template_controller', '_startup_template_preset', False),
    ('_try_apply_startup_template_if_ready', 'app.video_editor_startup_template_controller', '_try_apply_startup_template_if_ready', False),
    ('_retire_thumbnail_extractor', 'app.video_editor_thumbnail_controller', 'retire_thumbnail_extractor', False),
    ('_start_thumbnail_extraction', 'app.video_editor_thumbnail_controller', 'start_thumbnail_extraction', False),
    ('_on_thumb_count', 'app.video_editor_thumbnail_controller', 'on_thumb_count', False),
    ('_on_thumb_ready', 'app.video_editor_thumbnail_controller', 'on_thumb_ready', False),
    ('_on_extractor_done', 'app.video_editor_thumbnail_controller', 'on_extractor_done', False),
    ('_start_thumbnail_extraction_for_clip', 'app.video_editor_thumbnail_controller', 'start_thumbnail_extraction_for_clip', False),
    ('_on_clip_thumb_count', 'app.video_editor_thumbnail_controller', 'on_clip_thumb_count', False),
    ('_on_clip_thumb_ready', 'app.video_editor_thumbnail_controller', 'on_clip_thumb_ready', False),
    ('_on_clip_extractor_done', 'app.video_editor_thumbnail_controller', 'on_clip_extractor_done', False),
    ('_owner_original_source', 'app.video_editor_proxy_controller', 'owner_original_source', True),
    ('_fresh_proxy_for', 'app.video_editor_proxy_controller', 'fresh_proxy_for', False),
    ('_apply_proxy_owner', 'app.video_editor_proxy_controller', 'apply_proxy_owner', True),
    ('_active_proxy_source_path', 'app.video_editor_proxy_controller', 'active_proxy_source_path', False),
    ('_proxy_status_for_path', 'app.video_editor_proxy_controller', 'proxy_status_for_path', False),
    ('_refresh_proxy_status_ui', 'app.video_editor_proxy_controller', 'refresh_proxy_status_ui', False),
    ('_toggle_proxy_mode', 'app.video_editor_proxy_controller', 'toggle_proxy_mode', False),
    ('_start_proxy_generation', 'app.video_editor_proxy_controller', 'start_proxy_generation', False),
    ('_queue_auto_proxy_generation', 'app.video_editor_proxy_controller', 'queue_auto_proxy_generation', False),
    ('_on_proxy_done', 'app.video_editor_proxy_controller', 'on_proxy_done', False),
    ('_on_proxy_failed', 'app.video_editor_proxy_controller', 'on_proxy_failed', False),
    ('_regenerate_proxy_for_active_source', 'app.video_editor_proxy_controller', 'regenerate_proxy_for_active_source', False),
    ('_delete_proxy_for_active_source', 'app.video_editor_proxy_controller', 'delete_proxy_for_active_source', False),
    ('_autosave_path', 'app.video_editor_project_workflow', '_autosave_path', False),
    ('_current_project_name', 'app.video_editor_project_workflow', '_current_project_name', False),
    ('_do_autosave', 'app.video_editor_project_workflow', '_do_autosave', False),
    ('_do_autosave_legacy', 'app.video_editor_project_workflow', '_do_autosave_legacy', False),
    ('_draw_preview_placeholder', 'app.video_editor_preview_placeholder', '_draw_preview_placeholder', False),
    ('_set_preview_placeholder', 'app.video_editor_preview_placeholder', '_set_preview_placeholder', False),
    ('_clear_preview_placeholder', 'app.video_editor_preview_placeholder', '_clear_preview_placeholder', False),
    ('_preview_has_visual_content', 'app.video_editor_preview_placeholder', '_preview_has_visual_content', False),
    ('_refresh_visual_preview_after_timeline_change', 'app.video_editor_preview_placeholder', '_refresh_visual_preview_after_timeline_change', False),
    ('_update_preview_placeholder', 'app.video_editor_preview_placeholder', '_update_preview_placeholder', False),
    ('_import_media_from_empty_preview', 'app.video_editor_preview_placeholder', '_import_media_from_empty_preview', False),
    ('_active_renderable_clip_at_current_position', 'app.video_editor_preview_placeholder', '_active_renderable_clip_at_current_position', False),
    ('_preview_cpu_frame_consumers_active', 'app.video_editor_preview_frame_workflow', '_preview_cpu_frame_consumers_active', False),
    ('_refresh_preview_soft', 'app.video_editor_preview_frame_workflow', '_refresh_preview_soft', False),
    ('_preview_qimage_primary_active', 'app.video_editor_preview_frame_workflow', '_preview_qimage_primary_active', False),
    ('_refresh_preview_qimage_mode', 'app.video_editor_preview_frame_workflow', '_refresh_preview_qimage_mode', False),
    ('_latest_preview_qimage', 'app.video_editor_preview_frame_workflow', '_latest_preview_qimage', False),
    ('_qimage_from_preview_rgb', 'app.video_editor_preview_frame_workflow', '_qimage_from_preview_rgb', True),
    ('_on_frame_ready', 'app.video_editor_preview_frame_workflow', '_on_frame_ready', False),
    ('_ensure_preview_gl', 'app.video_editor_preview_frame_workflow', '_ensure_preview_gl', False),
    ('_prewarm_preview_gl_surface', 'app.video_editor_preview_frame_workflow', '_prewarm_preview_gl_surface', False),
    ('_on_gpu_frame_ready', 'app.video_editor_preview_frame_workflow', '_on_gpu_frame_ready', False),
    ('_on_spine_gpu_overlay_failed', 'app.video_editor_preview_frame_workflow', '_on_spine_gpu_overlay_failed', False),
    ('_has_recoverable_project_state', 'app.video_editor_project_workflow', '_has_recoverable_project_state', False),
    ('_on_batch_export', 'app.video_editor_export_workflow', '_on_batch_export', False),
    ('_on_export', 'app.video_editor_export_workflow', '_on_export', False),
    ('_on_export_live2d_only', 'app.video_editor_export_workflow', '_on_export_live2d_only', False),
    ('_refresh_export_button_tooltip', 'app.video_editor_export_workflow', '_refresh_export_button_tooltip', False),
    ('_refresh_quality_btn_label', 'app.video_editor_export_workflow', '_refresh_quality_btn_label', False),
    ('_build_quality_menu', 'app.video_editor_export_workflow', '_build_quality_menu', False),
    ('_on_quality_picked', 'app.video_editor_export_workflow', '_on_quality_picked', False),
    ('_refresh_format_btn_label', 'app.video_editor_export_workflow', '_refresh_format_btn_label', False),
    ('_build_format_menu', 'app.video_editor_export_workflow', '_build_format_menu', False),
    ('_on_format_picked', 'app.video_editor_export_workflow', '_on_format_picked', False),
    ('_refresh_resolution_btn_label', 'app.video_editor_export_workflow', '_refresh_resolution_btn_label', False),
    ('_build_resolution_menu', 'app.video_editor_export_workflow', '_build_resolution_menu', False),
    ('_on_resolution_picked', 'app.video_editor_export_workflow', '_on_resolution_picked', False),
    ('_refresh_fps_btn_label', 'app.video_editor_export_workflow', '_refresh_fps_btn_label', False),
    ('_build_fps_menu', 'app.video_editor_export_workflow', '_build_fps_menu', False),
    ('_on_fps_picked', 'app.video_editor_export_workflow', '_on_fps_picked', False),
    ('_on_new_project', 'app.video_editor_project_workflow', '_on_new_project', False),
    ('_on_open_project', 'app.video_editor_project_workflow', '_on_open_project', False),
    ('_on_relink_project_media', 'app.video_editor_project_workflow', '_on_relink_project_media', False),
    ('_on_save_project', 'app.video_editor_project_workflow', '_on_save_project', False),
    ('_open_visual_qa_viewer', 'app.video_editor_visual_qa_workflow', '_open_visual_qa_viewer', False),
    ('_proxy_thread_key', 'app.video_editor_proxy_controller', '_proxy_thread_key', True),
    ('_on_blur_params_changed', 'app.video_editor_render_chain_workflow', '_on_blur_params_changed', False),
    ('_on_effect_params_changed', 'app.video_editor_render_chain_workflow', '_on_effect_params_changed', False),
    ('_rebuild_active_chain', 'app.video_editor_render_chain_workflow', '_rebuild_active_chain', False),
    ('_tracking_cache_source_for_track', 'app.video_editor_render_chain_workflow', '_tracking_cache_source_for_track', False),
    ('_prewarm_tracking_caches_for_track', 'app.video_editor_render_chain_workflow', '_prewarm_tracking_caches_for_track', False),
    ('_on_tracking_cache_ready', 'app.video_editor_render_chain_workflow', '_on_tracking_cache_ready', False),
    ('_on_tracking_cache_failed', 'app.video_editor_render_chain_workflow', '_on_tracking_cache_failed', False),
    ('_retire_tracking_cache_worker', 'app.video_editor_render_chain_workflow', '_retire_tracking_cache_worker', False),
    ('_start_preview_prerender_for_track', 'app.video_editor_render_chain_workflow', '_start_preview_prerender_for_track', False),
    ('_cancel_preview_prerender_jobs', 'app.video_editor_render_chain_workflow', '_cancel_preview_prerender_jobs', False),
    ('_retire_preview_prerender_worker', 'app.video_editor_render_chain_workflow', '_retire_preview_prerender_worker', False),
    ('_recovery_dir', 'app.video_editor_project_workflow', '_recovery_dir', False),
    ('_refresh_window_title', 'app.video_editor_project_workflow', '_refresh_window_title', False),
    ('_screenstudio_export_defaults_for_current_project', 'app.video_editor_export_workflow', '_screenstudio_export_defaults_for_current_project', False),
    ('_screenstudio_post_export_handoff_note', 'app.video_editor_export_workflow', '_screenstudio_post_export_handoff_note', False),
    ('_screenstudio_write_local_share_package', 'app.video_editor_export_workflow', '_screenstudio_write_local_share_package', False),
    ('_show_export_final_checklist', 'app.video_editor_export_workflow', '_show_export_final_checklist', False),
    ('_show_media_health', 'app.video_editor_project_workflow', '_show_media_health', False),
    ('_show_recovery_candidates', 'app.video_editor_project_workflow', '_show_recovery_candidates', False),
    ('_snapshot_clip_effects_for_export', 'app.video_editor_export_snapshot', 'snapshot_clip_effects_for_export', True),
    ('_snapshot_node_item_chain_for_export', 'app.video_editor_export_snapshot', 'snapshot_node_item_chain_for_export', True),
    ('_export_zoom_actors_for_track', 'app.video_editor_render_chain_workflow', '_export_zoom_actors_for_track', True),
    ('_write_recovery_snapshot', 'app.video_editor_project_workflow', '_write_recovery_snapshot', False),
)

_BROADCAST_WORKFLOW_NAMES = (
    '_open_vtuber_broadcast_studio',
    '_broadcast_output_canvas',
    '_broadcast_output_session_status',
    '_start_broadcast_live_target',
    '_start_broadcast_audio_mixdown_if_needed',
    '_on_broadcast_audio_mixdown_progress',
    '_on_broadcast_audio_mixdown_finished',
    '_prepare_broadcast_live_target_audio',
    '_stop_broadcast_live_target',
    '_feed_broadcast_output_frame',
    '_update_vtuber_studio_live_session_status',
)


def install_media_preview_export_delegates(VideoEditorWindow) -> None:
    bind_imported_delegate_methods(VideoEditorWindow, _BINDINGS)
    for name in _BROADCAST_WORKFLOW_NAMES:
        setattr(VideoEditorWindow, name, getattr(_broadcast_workflow, name))
