from __future__ import annotations


OBJECT_ITEMS = (
    ("Text", "text"),
    ("Image", "image"),
    ("Shape", "shape"),
    ("Polygon", "polygon"),
    ("Star", "star"),
    ("Path", "path"),
    ("Line", "line"),
    ("Group", "group"),
    ("Null", "null"),
    ("Adjustment", "adjustment"),
    ("Generator", "generator"),
    ("3D Object", "ar_pbr"),
    ("Live2D Actor", "live2d_actor"),
    ("Spine Actor", "spine_actor"),
    ("MMD Actor", "mmd_actor"),
    ("VRM Avatar", "vrm_actor"),
    ("Particle Emitter", "particle"),
    ("Camera", "camera"),
    ("Light", "light"),
)

BEHAVIOR_ITEMS = (
    ("Fade", "fade"),
    ("Slide", "slide"),
    ("Pop", "pop"),
    ("Spring", "spring"),
    ("Wiggle", "wiggle"),
    ("Impact", "impact"),
    ("Spin", "spin"),
    ("Drift", "drift"),
    ("Grow / Shrink", "grow_shrink"),
    ("Oscillate", "oscillate"),
    ("Random Motion", "random_motion"),
)

FILTER_ITEMS = (
    ("Glow", "glow"),
    ("Gaussian Blur", "gaussian_blur"),
    ("Brightness / Contrast", "brightness_contrast"),
    ("Saturation", "saturation"),
    ("Vignette", "vignette"),
    ("Unsharp Mask", "unsharp_mask"),
    ("Directional Blur", "directional_blur"),
    ("Displacement", "displacement"),
    ("Corner Pin", "corner_pin"),
    ("Mesh Warp", "mesh_warp"),
    ("Paper Fold", "paper_fold"),
    ("Paper Crumple", "paper_crumple"),
    ("Scan Cleanup", "scan_cleanup"),
    ("Craft / Imperfection", "craft_style"),
    ("Painterly / Toon / Ink", "painterly_look"),
)

CATALOG = {
    "Objects": tuple((label, "object", kind) for label, kind in OBJECT_ITEMS),
    "Generators": (
        ("Solid Color", "generator", "solid"),
        ("Gradient", "generator", "gradient"),
        ("Checkerboard", "generator", "checkerboard"),
        ("Grid", "generator", "grid"),
        ("Noise", "generator", "noise"),
        ("Rays", "generator", "rays"),
    ),
    "Tiger Repeaters": (
        ("Linear Tiger Repeater", "replicator", "line"),
        ("Grid Tiger Repeater", "replicator", "grid"),
        ("Radial Tiger Repeater", "replicator", "radial"),
    ),
    "Behaviors": tuple((label, "behavior", kind) for label, kind in BEHAVIOR_ITEMS),
    "Filters": tuple((label, "effect", kind) for label, kind in FILTER_ITEMS),
    "Templates": (
        ("Clean Lower Third", "template", "clean_lower_third"),
        ("Character Nameplate", "template", "character_nameplate"),
        ("Logo Reveal", "template", "logo_reveal"),
        ("City After Rain", "template", "studio_city_after_rain"),
        ("Artisan Coffee Launch", "template", "studio_artisan_coffee"),
        ("Alpine Travel Journal", "template", "studio_alpine_journal"),
        ("Paper Crumple & Unfold", "template", "paper_crumple_unfold"),
        ("Product Callout", "template", "product_callout"),
        ("Stream Stinger", "template", "stream_stinger"),
        ("Music Beat Title", "template", "music_beat_title"),
        ("Vertical Shorts Hook", "template", "vertical_shorts_hook"),
        ("Anime Character Intro", "template", "anime_character_intro"),
        ("MMD Dance Title", "template", "mmd_dance_title"),
        ("VRM Stream Starting / Ending", "template", "vrm_stream_starting_ending"),
        ("iOS App UI Motion Kit", "template", "ios_app_ui_motion_kit"),
        ("Mobile Onboarding Flow", "template", "mobile_onboarding_flow"),
        ("Responsive SaaS Product Tour", "template", "responsive_saas_product_tour"),
        ("Product Launch Ad - 15 Seconds", "template", "product_launch_ad_15s"),
        ("Vertical Social Ad - 15 Seconds", "template", "vertical_social_ad_15s"),
        ("Campaign Story Ad - 30 Seconds", "template", "campaign_story_ad_30s"),
        ("Course Module Opener - 20 Seconds", "template", "course_module_opener_20s"),
        ("Step-by-Step Tutorial - 45 Seconds", "template", "step_by_step_tutorial_45s"),
        ("Lesson Explainer - 60 Seconds", "template", "lesson_explainer_60s"),
        ("Learn Generators and Tiger Repeaters", "template", "learn_generators_replicators"),
    ),
    "Direction Presets": (
        ("Headline Slam", "advanced_preset", "headline_slam"),
        ("Paper Rip Reveal", "advanced_preset", "paper_rip_reveal"),
        ("Paper Crumple & Unfold", "advanced_preset", "paper_crumple_unfold"),
        ("Cutout Collage", "advanced_preset", "cutout_collage"),
        ("Editorial Camera Push", "advanced_preset", "editorial_camera_push"),
        ("Beat-Synced Montage", "advanced_preset", "beat_synced_montage"),
    ),
    "Mixed Media": (
        ("Editorial Collage", "collage", "editorial:torn:tape"),
        ("Luxury Paper", "collage", "luxury:feather:fold"),
        ("Education Cutaway", "collage", "education:fiber:staple"),
        ("Loose Scatter", "collage", "scatter:torn:pin"),
    ),
}

CATEGORY_LABELS = {
    "Objects": "Objects",
    "Generators": "Generators",
    "Tiger Repeaters": "Tiger Repeaters",
    "Behaviors": "Animation",
    "Filters": "Effects",
    "Templates": "Templates",
    "Direction Presets": "Motion Presets",
    "Mixed Media": "Mixed Media",
}

CATEGORY_HINTS = {
    "Objects": "Add a new editable layer",
    "Generators": "Create a procedural full-frame source",
    "Tiger Repeaters": "Repeat the selected layer with Tiger's deterministic pattern subset",
    "Behaviors": "Animate the selected layer",
    "Filters": "Style the selected layer",
    "Templates": "Replace the current composition",
    "Direction Presets": "Apply a designed motion treatment",
    "Mixed Media": "Build an editable paper, scan, and collage treatment",
}

ITEM_DESCRIPTIONS = {
    "text": "Animated titles, captions, and typography",
    "image": "Photo, artwork, texture, or cutout layer",
    "shape": "Editable rectangle or ellipse",
    "polygon": "Editable multi-sided vector shape",
    "star": "Editable star or burst shape",
    "path": "Draw and animate a Bezier path",
    "line": "Stroke, divider, or animated line",
    "group": "Organize and transform layers together",
    "null": "Invisible parent and animation controller",
    "adjustment": "Apply effects to layers below",
    "generator": "Procedural solid, gradient, pattern, noise, or rays",
    "solid": "A flat procedural color source",
    "gradient": "A procedural two-color linear gradient",
    "checkerboard": "A scalable two-color checker pattern",
    "grid": "A procedural line grid",
    "noise": "Deterministic procedural noise",
    "rays": "Radial alternating color rays",
    "radial": "Repeat the selected layer around a circle",
    "ar_pbr": "Lighting-aware 3D model layer",
    "live2d_actor": "Live2D character actor",
    "spine_actor": "Spine character actor",
    "mmd_actor": "MMD model and motion actor",
    "vrm_actor": "VRM avatar actor",
    "particle": "GPU particle emitter",
    "camera": "Animate composition framing",
    "light": "Light supported 3D layers",
    "fade": "Fade the selected layer in or out",
    "slide": "Move the selected layer on or off screen",
    "pop": "Quick scale emphasis",
    "spring": "Overshoot and settle naturally",
    "wiggle": "Continuous position or rotation variation",
    "impact": "Fast editorial hit animation",
    "glow": "Soft luminous edge and bloom",
    "gaussian_blur": "Smooth image blur",
    "brightness_contrast": "Adjust tonal range",
    "saturation": "Adjust color intensity",
    "vignette": "Darken or soften frame edges",
    "unsharp_mask": "Increase local sharpness",
    "directional_blur": "Motion-oriented blur",
    "displacement": "Warp pixels with a source map",
    "corner_pin": "Fit a layer to four points",
    "mesh_warp": "Deform a layer with a mesh",
    "paper_fold": "Simulate a folding paper surface",
    "paper_crumple": "Crumple and unfold paper with editable residual wrinkles",
    "scan_cleanup": "Balance scanned paper, preserve ink, and remove paper",
    "craft_style": "Deterministic film grain, gate weave, and light flicker",
    "painterly_look": "Stable toon bands, ink lines, brush texture, and paper",
}
