from __future__ import annotations

import argparse
import base64
import json
import mimetypes
import re
import sys
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_ROOT = ROOT.parent / "ReviewAutomationWorkspace" / "source_assets" / "templates"
DEBUG_ROOT = ROOT.parent / "ReviewAutomationWorkspace" / "outputs" / "template_debug" / "screen_map_calibration"

DEFAULT_TEMPLATE = TEMPLATE_ROOT / "multi_monitor_front_facing_catalog_template_v2_tight.png"
DEFAULT_SCREEN_MAP = DEFAULT_TEMPLATE.with_suffix(".screen-map.json")
APP_HTML = Path(__file__).with_name("screen_map_calibrator_web.html")


def _load_regions(payload: dict[str, Any]) -> list[dict[str, Any]]:
    raw = payload.get("screen_regions")
    if isinstance(raw, list):
        return [item for item in raw if isinstance(item, dict)]
    raw_by_id = payload.get("regions")
    regions: list[dict[str, Any]] = []
    if isinstance(raw_by_id, dict):
        for region_id, value in raw_by_id.items():
            if isinstance(value, dict):
                item = dict(value)
                item.setdefault("id", region_id)
                regions.append(item)
    return regions


def _image_size(path: Path) -> dict[str, int]:
    try:
        from PIL import Image

        with Image.open(path) as image:
            return {"width": int(image.width), "height": int(image.height)}
    except Exception:
        return {"width": 0, "height": 0}


def _safe_region(item: dict[str, Any]) -> dict[str, Any] | None:
    region_id = str(item.get("id") or "").strip()
    rect = item.get("rect")
    if not region_id or not isinstance(rect, dict):
        return None
    try:
        x = int(round(float(rect.get("x", 0))))
        y = int(round(float(rect.get("y", 0))))
        width = max(1, int(round(float(rect.get("width", 1)))))
        height = max(1, int(round(float(rect.get("height", 1)))))
    except Exception:
        return None
    return {
        "id": region_id,
        "rect": {"x": x, "y": y, "width": width, "height": height},
        "fit": str(item.get("fit") or "cover"),
        "mapping": str(item.get("mapping") or "rect"),
        "notes": str(item.get("notes") or ""),
    }


def build_payload(template_path: Path, screen_map_path: Path, incoming_regions: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    if incoming_regions is None and screen_map_path.exists():
        source = json.loads(screen_map_path.read_text(encoding="utf-8"))
        incoming_regions = _load_regions(source)
    if incoming_regions is None:
        incoming_regions = [
            {"id": "left_monitor", "rect": {"x": 552, "y": 333, "width": 325, "height": 222}},
            {"id": "center_monitor", "rect": {"x": 892, "y": 333, "width": 325, "height": 222}},
            {"id": "right_monitor", "rect": {"x": 1232, "y": 333, "width": 325, "height": 222}},
        ]
    regions = [safe for item in incoming_regions if (safe := _safe_region(item))]
    return {
        "schema": "tiger.review.template.screen_map.calibrated.v1",
        "template": template_path.name,
        "image_size": _image_size(template_path),
        "screen_regions": regions,
        "regions": {
            region["id"]: {
                "rect": region["rect"],
                "fit": region["fit"],
                "mapping": region["mapping"],
                "notes": region["notes"],
            }
            for region in regions
        },
        "rules": [
            "Generated by tools/screen_map_calibrator_web.py.",
            "Replace only declared screen regions with real TigerCapture captures.",
            "Do not distort template hardware.",
        ],
    }


class CalibratorServer(ThreadingHTTPServer):
    def __init__(self, server_address: tuple[str, int], handler: type[BaseHTTPRequestHandler], template_path: Path, screen_map_path: Path) -> None:
        super().__init__(server_address, handler)
        self.template_path = template_path
        self.screen_map_path = screen_map_path


class Handler(BaseHTTPRequestHandler):
    server: CalibratorServer

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path in {"/", "/index.html"}:
            self._send_file(APP_HTML, "text/html; charset=utf-8")
            return
        if parsed.path == "/image":
            self._send_file(self.server.template_path, mimetypes.guess_type(self.server.template_path.name)[0] or "image/png")
            return
        if parsed.path == "/api/state":
            payload = build_payload(self.server.template_path, self.server.screen_map_path)
            payload["template_path"] = str(self.server.template_path)
            payload["screen_map_path"] = str(self.server.screen_map_path)
            self._send_json(payload)
            return
        self.send_error(HTTPStatus.NOT_FOUND, "not found")

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/save":
            self._handle_save()
            return
        if parsed.path == "/api/export-preview":
            self._handle_export_preview()
            return
        self.send_error(HTTPStatus.NOT_FOUND, "not found")

    def log_message(self, format: str, *args: Any) -> None:
        sys.stderr.write("%s - %s\n" % (self.address_string(), format % args))

    def _read_json(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(length)
        return json.loads(raw.decode("utf-8")) if raw else {}

    def _handle_save(self) -> None:
        try:
            request = self._read_json()
            regions = request.get("screen_regions")
            if not isinstance(regions, list):
                raise ValueError("screen_regions must be a list")
            payload = build_payload(self.server.template_path, self.server.screen_map_path, regions)
            self.server.screen_map_path.parent.mkdir(parents=True, exist_ok=True)
            self.server.screen_map_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            self._send_json({"ok": True, "path": str(self.server.screen_map_path), "screen_regions": payload["screen_regions"]})
        except Exception as exc:
            self._send_json({"ok": False, "error": str(exc)}, status=HTTPStatus.BAD_REQUEST)

    def _handle_export_preview(self) -> None:
        try:
            request = self._read_json()
            data_url = str(request.get("data_url") or "")
            match = re.match(r"^data:image/png;base64,(.+)$", data_url)
            if not match:
                raise ValueError("expected PNG data_url")
            DEBUG_ROOT.mkdir(parents=True, exist_ok=True)
            out = DEBUG_ROOT / f"{self.server.template_path.stem}_web_calibration_preview.png"
            out.write_bytes(base64.b64decode(match.group(1)))
            self._send_json({"ok": True, "path": str(out)})
        except Exception as exc:
            self._send_json({"ok": False, "error": str(exc)}, status=HTTPStatus.BAD_REQUEST)

    def _send_file(self, path: Path, content_type: str) -> None:
        if not path.exists():
            self.send_error(HTTPStatus.NOT_FOUND, f"missing file: {path}")
            return
        payload = path.read_bytes()
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(payload)

    def _send_json(self, payload: dict[str, Any], status: HTTPStatus = HTTPStatus.OK) -> None:
        raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(raw)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the TigerCapture screen-map web calibrator.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8797)
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--screen-map", type=Path, default=DEFAULT_SCREEN_MAP)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    template = args.template.resolve()
    screen_map = args.screen_map.resolve()
    if not template.exists():
        raise FileNotFoundError(template)
    server = CalibratorServer((args.host, args.port), Handler, template, screen_map)
    print(f"Screen map calibrator running at http://{args.host}:{args.port}/")
    print(f"template={template}")
    print(f"screen_map={screen_map}")
    server.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
