"""PPT animation compatibility QA deck generation."""
from __future__ import annotations

import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.pptgen.editing import set_element_animation
from app.pptgen.pdf_export import (
    convert_pptx_to_pdf_with_libreoffice,
    convert_pptx_to_pdf_with_powerpoint_com,
    find_libreoffice_executable as _find_libreoffice_executable,
)
from app.pptgen.preview import render_contact_sheet, render_deck_pngs
from app.pptgen.project_io import save_deck_project
from app.pptgen.schema import DeckSpec, ElementStyle, SlideElement, SlideSpec
from app.pptgen.writer_python_pptx import write_pptx_compatible


def _text(element_id: str, text: str, *, x: float, y: float, w: float, h: float, size: int = 24, color: str = "#182033", bold: bool = False) -> SlideElement:
    return SlideElement.text_box(element_id, text, x=x, y=y, w=w, h=h, font_size=size, color=color, bold=bold)


def _box(element_id: str, label: str, *, x: float, y: float, fill: str, stroke: str = "#182033") -> SlideElement:
    return SlideElement(
        id=element_id,
        kind="shape",
        name=label,
        x=x,
        y=y,
        w=0.17,
        h=0.15,
        style=ElementStyle(fill=fill, stroke=stroke, stroke_width=1.4, color="#182033", font_size=18),
    )


def build_animation_qa_deck() -> DeckSpec:
    deck = DeckSpec(id="ppt-animation-compat-qa", title="PPT Animation Compatibility QA", purpose="qa")
    deck.metadata.update(
        {
            "qa_kind": "ppt_animation_compat",
            "expected_effects": ["appear", "fade_in", "fade_out", "move", "scale", "on_click"],
            "manual_check_summary": "Open the PPTX in PowerPoint/LibreOffice and verify simple animation timing/order.",
        }
    )

    slide1 = SlideSpec(id="slide-001", title="QA instructions", layout_id="qa-cover", duration_ms=5500, background="#FFFFFF")
    slide1.add_element(_text("s1-title", "PPT Animation Compatibility QA", x=0.07, y=0.10, w=0.78, h=0.12, size=42, bold=True))
    slide1.add_element(
        _text(
            "s1-body",
            "This deck is generated by TigerCapture to verify native PPTX timing XML and editor preview parity.\n"
            "Check fade/appear/move/scale timing, then click-triggered effects on slide 3.",
            x=0.08,
            y=0.28,
            w=0.74,
            h=0.22,
            size=23,
            color="#354052",
        )
    )
    slide1.add_element(_box("s1-badge", "QA", x=0.74, y=0.56, fill="#EAF1FF", stroke="#2F6FED"))
    deck.slides.append(slide1)
    set_element_animation(deck, "s1-title", slide_id=slide1.id, in_animation="fade_in", start_ms=150, duration_ms=650)
    set_element_animation(deck, "s1-badge", slide_id=slide1.id, in_animation="scale", start_ms=900, duration_ms=650, scale=0.45)

    slide2 = SlideSpec(id="slide-002", title="Auto-timed effects", layout_id="qa-effects", duration_ms=5200, background="#FFFFFF")
    slide2.add_element(_text("s2-title", "Auto-timed effects", x=0.06, y=0.06, w=0.72, h=0.08, size=34, bold=True))
    deck.slides.append(slide2)
    effects = [
        ("s2-appear", "Appear", 0.07, "#EAF1FF", "appear", 250, 1, {}),
        ("s2-fade-in", "Fade In", 0.27, "#E9F8EF", "fade_in", 850, 700, {}),
        ("s2-fade-out", "Fade Out", 0.47, "#FFF0E8", "fade_out", 1600, 750, {}),
        ("s2-move", "Move", 0.67, "#F2ECFF", "move", 2350, 800, {"motion_x": -0.18, "motion_y": 0.0}),
        ("s2-scale", "Scale", 0.37, "#EAF8FF", "scale", 3300, 700, {"scale": 0.35}),
    ]
    for element_id, label, x, fill, effect, start_ms, duration_ms, extras in effects:
        y = 0.27 if element_id != "s2-scale" else 0.56
        box = _box(element_id, label, x=x, y=y, fill=fill, stroke="#2F6FED")
        slide2.add_element(box)
        slide2.add_element(_text(f"{element_id}-label", f"{label}\n{start_ms}ms", x=x, y=y + 0.18, w=0.17, h=0.09, size=15, color="#5E6A7D"))
        set_element_animation(deck, element_id, slide_id=slide2.id, in_animation=effect, start_ms=start_ms, duration_ms=duration_ms, **extras)

    slide3 = SlideSpec(id="slide-003", title="Click-triggered effects", layout_id="qa-click", duration_ms=6200, background="#FFFFFF")
    slide3.add_element(_text("s3-title", "Click-triggered effects", x=0.06, y=0.06, w=0.72, h=0.08, size=34, bold=True))
    slide3.add_element(
        _text(
            "s3-note",
            "In PowerPoint, advance the slide and click twice. The two cards should appear/fade after clicks.",
            x=0.07,
            y=0.18,
            w=0.70,
            h=0.12,
            size=20,
            color="#354052",
        )
    )
    click_a = _box("s3-click-appear", "Click Appear", x=0.18, y=0.43, fill="#EAF1FF", stroke="#2F6FED")
    click_b = _box("s3-click-fade", "Click Fade", x=0.48, y=0.43, fill="#E9F8EF", stroke="#3A8F5A")
    slide3.add_element(click_a)
    slide3.add_element(click_b)
    deck.slides.append(slide3)
    set_element_animation(deck, click_a.id, slide_id=slide3.id, in_animation="appear", trigger="on_click", start_ms=0, duration_ms=1)
    set_element_animation(deck, click_b.id, slide_id=slide3.id, in_animation="fade_in", trigger="on_click", start_ms=0, duration_ms=650)

    slide4 = SlideSpec(id="slide-004", title="Reference static slide", layout_id="qa-static", duration_ms=3500, background="#FFFFFF")
    slide4.add_element(_text("s4-title", "Reference static slide", x=0.06, y=0.08, w=0.72, h=0.10, size=36, bold=True))
    slide4.add_element(_text("s4-body", "This slide has no animation and should render as a normal static PPT slide.", x=0.08, y=0.28, w=0.68, h=0.18, size=24, color="#354052"))
    deck.slides.append(slide4)
    return deck


def inspect_pptx_animation_xml(path: str | Path) -> dict[str, int]:
    target = Path(path)
    counts = {
        "slide_count": 0,
        "slides_with_timing": 0,
        "anim_effect_count": 0,
        "set_effect_count": 0,
        "on_click_count": 0,
        "build_entry_count": 0,
    }
    with zipfile.ZipFile(target) as zf:
        for name in zf.namelist():
            if not name.startswith("ppt/slides/slide") or not name.endswith(".xml"):
                continue
            counts["slide_count"] += 1
            xml = zf.read(name).decode("utf-8", errors="replace")
            if "<p:timing>" in xml:
                counts["slides_with_timing"] += 1
            counts["anim_effect_count"] += xml.count("<p:animEffect")
            counts["set_effect_count"] += xml.count("<p:set>")
            counts["on_click_count"] += xml.count('evt="onClick"')
            counts["build_entry_count"] += xml.count("<p:bldP")
    return counts


def find_libreoffice_executable() -> str | None:
    return _find_libreoffice_executable()


def validate_with_libreoffice(
    pptx: str | Path,
    output_dir: str | Path,
    *,
    executable: str | None = None,
    timeout_sec: int = 60,
) -> dict[str, Any]:
    target = Path(pptx)
    out = Path(output_dir)
    resolved = executable if executable is not None else find_libreoffice_executable()
    if not resolved:
        return {
            "host": "libreoffice",
            "status": "skipped",
            "ok": False,
            "executable": "",
            "output_pdf": str(out / f"{target.stem}.pdf"),
            "reason": "LibreOffice executable not found",
        }
    return convert_pptx_to_pdf_with_libreoffice(
        target,
        out / f"{target.stem}.pdf",
        executable=resolved,
        timeout_sec=timeout_sec,
    )


def validate_with_powerpoint_com(
    pptx: str | Path,
    output_dir: str | Path,
    *,
    timeout_sec: int = 90,
) -> dict[str, Any]:
    target = Path(pptx).resolve()
    out = Path(output_dir).resolve()
    return convert_pptx_to_pdf_with_powerpoint_com(target, out / f"{target.stem}_powerpoint.pdf", timeout_sec=timeout_sec)


def run_host_validation(
    pptx: str | Path,
    output_dir: str | Path,
    *,
    host_check: str = "none",
    timeout_sec: int = 60,
) -> dict[str, Any]:
    mode = str(host_check or "none").strip().lower()
    result: dict[str, Any] = {
        "requested": mode,
        "results": [],
        "passed": False,
    }
    if mode in {"", "none", "off", "false"}:
        return result
    host_dir = Path(output_dir) / "host_validation"
    if mode in {"auto", "libreoffice"}:
        libre = validate_with_libreoffice(pptx, host_dir / "libreoffice", timeout_sec=timeout_sec)
        result["results"].append(libre)
        if libre.get("status") == "passed":
            result["passed"] = True
            if mode == "auto":
                return result
    if mode in {"auto", "powerpoint", "powerpoint_com"}:
        power = validate_with_powerpoint_com(pptx, host_dir / "powerpoint", timeout_sec=timeout_sec)
        result["results"].append(power)
        if power.get("status") == "passed":
            result["passed"] = True
    return result


def write_animation_qa_outputs(
    output_dir: str | Path,
    *,
    host_check: str = "none",
    require_host: bool = False,
    host_timeout_sec: int = 60,
) -> dict[str, Any]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    deck = build_animation_qa_deck()
    project = save_deck_project(deck, out / "ppt_animation_compat_qa.tgppt")
    pptx = write_pptx_compatible(deck, out / "ppt_animation_compat_qa.pptx")
    slide_dir = out / "slides"
    pngs = render_deck_pngs(deck, slide_dir)
    contact_sheet = render_contact_sheet(deck, out / "contact_sheet.png")
    inspection = inspect_pptx_animation_xml(pptx)
    host_validation = run_host_validation(pptx, out, host_check=host_check, timeout_sec=host_timeout_sec)
    static_ok = bool(
        inspection["slide_count"] == len(deck.slides)
        and inspection["slides_with_timing"] >= 3
        and inspection["anim_effect_count"] >= 5
        and inspection["set_effect_count"] >= 1
        and inspection["on_click_count"] >= 2
    )
    manifest_path = out / "manifest.json"
    manifest = {
        "schema": "tigercapture.ppt_animation_compat_qa.v1",
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "ok": bool(static_ok and (not require_host or host_validation.get("passed"))),
        "paths": {
            "project": str(project),
            "pptx": str(pptx),
            "slides_dir": str(slide_dir),
            "contact_sheet": str(contact_sheet),
            "manifest": str(manifest_path),
        },
        "slide_png_count": len(pngs),
        "ooxml_static_checks": inspection,
        "host_validation": {
            **host_validation,
            "required": bool(require_host),
        },
        "manual_checks": [
            "Open ppt_animation_compat_qa.pptx in PowerPoint and start slideshow.",
            "Slide 1: title fades in and QA badge scales in.",
            "Slide 2: appear, fade-in, fade-out, move, and scale effects occur in order.",
            "Slide 3: two click-triggered cards reveal after user clicks.",
            "Open in LibreOffice/WPS if available and record any degraded effects.",
        ],
        "known_limits": [
            "This QA verifies generated OOXML timing presence and manual host compatibility, not pixel-perfect PowerPoint playback.",
            "Move/scale parity may vary by host; TigerCapture preview remains the product-side reference until host-specific mapping is hardened.",
        ],
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return manifest

__all__ = [
    "build_animation_qa_deck",
    "find_libreoffice_executable",
    "inspect_pptx_animation_xml",
    "run_host_validation",
    "validate_with_libreoffice",
    "validate_with_powerpoint_com",
    "write_animation_qa_outputs",
]
